/** AUTO-GENERATED by scripts/import-portfolio.mjs — do not edit */
import type { PortfolioVideo } from "./video-catalog";

export const PORTFOLIO_VIDEO_CATALOG: readonly PortfolioVideo[] = [
  {
    "videoId": "P425XNK7z5M",
    "title": "כותבים ראפ באולפן - Flow, Bars ובנייה מאפס",
    "youtubeUrl": "https://www.youtube.com/shorts/P425XNK7z5M",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "recording-song-modiin",
      "studio-hub"
    ]
  },
  {
    "videoId": "XiiOcx8doz0",
    "title": "פודקאסט מרפסת: יקיר כהן ומאור קמחי בודקים - האם מאור מגדלור הוא הדבר הבא? (אורח הכבוד יקיר איזמירלי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=XiiOcx8doz0",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "cengTHzov5I",
    "title": "איך לקבוע פודקאסט עם אמנים גדולים? (ולמה המנהלים שלהם מסננים אתכם)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cengTHzov5I",
    "tags": [
      "podcast",
      "education"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "1O0isV7Zljg",
    "title": "אותו מוצר, מחיר שונה לכל לקוח? האמת על תמחור ולקוחות \"קשים\"",
    "youtubeUrl": "https://www.youtube.com/watch?v=1O0isV7Zljg",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "AXIzb0XrITs",
    "title": "האם יעל פוליאקוב צדקה? | מתי \"שמנה\" הופכת לקללה והאמת מאחורי סרטוני ה\"לוקים\"",
    "youtubeUrl": "https://www.youtube.com/watch?v=AXIzb0XrITs",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "9j799KKjdT0",
    "title": "האם AI יכול להחליף מפיק מוזיקלי? שיחה עמוקה, מצחיקה ומטורפת על יצירה, טכנולוגיה והעתיד",
    "youtubeUrl": "https://www.youtube.com/watch?v=9j799KKjdT0",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "zkyPqV7m4Q8",
    "title": "איך כותבים לעומר אדם? כותב הלהיטים אליה רוסיליו חושף את כל הסודות | זמן להכיר",
    "youtubeUrl": "https://www.youtube.com/watch?v=zkyPqV7m4Q8",
    "tags": [
      "brand-tv",
      "podcast",
      "education"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "8i4K2f5gQfM",
    "title": "הקלטת שיר לחתונה  שיר מקורי ומרגש לחופה שיזיל דמעות (קאבר עם הפקה מותאמת אישית)",
    "youtubeUrl": "https://www.youtube.com/watch?v=8i4K2f5gQfM",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "XUr2e5S4JSA",
    "title": "אולפן הקלטות במודיעין כל המפורסמים שביקרו והקליטו אצלנו + סיור בסטודיו (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=XUr2e5S4JSA",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "9jkngkiEr9I",
    "title": "האם מלך אמיתי צריך לחשוף את כל הסודות שלו?",
    "youtubeUrl": "https://www.youtube.com/watch?v=9jkngkiEr9I",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "zjoXk7QuLzY",
    "title": "כל אחד יכול לעשות פודקאסט? הדיון שחובה להשתתף בו + הסוד האמיתי מאחורי ה-AI שמחליף מפיקים!",
    "youtubeUrl": "https://www.youtube.com/watch?v=zjoXk7QuLzY",
    "tags": [
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub"
    ]
  },
  {
    "videoId": "2apMsrmEsDs",
    "title": "שיר כניסה לחופה: הקלטה מקצועית ושדרוג קולי לחתן ולכלה",
    "youtubeUrl": "https://www.youtube.com/watch?v=2apMsrmEsDs",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "dr-LIAcXll0",
    "title": "פרופ' אמיר חצרוני ואיזמירלי: 🔔 למה הוא נגד מדינה יהודית? | האח הגדול, טיקטוק וזמרים מזרחיים",
    "youtubeUrl": "https://www.youtube.com/watch?v=dr-LIAcXll0",
    "tags": [
      "brand-tv"
    ],
    "services": [
      "podcast-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "0XXeBgOm4XA",
    "title": "מחירי אולפני הקלטות - מה באמת קובע את המחיר ( שירות, זמן או תוצאה? )",
    "youtubeUrl": "https://www.youtube.com/watch?v=0XXeBgOm4XA",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "c55HTqTArFo",
    "title": "אולפן הקלטות במודיעין | שווה להגיע גם מחיפה והקריות? (איך נראה האולפן?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=c55HTqTArFo",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "mnDVjrt7xPA",
    "title": "האם כל הלחנים יגמרו? אלגוריתם מוזיקה, זכויות יוצרים ויצירתיות | יצירתיות מוזיקלית",
    "youtubeUrl": "https://www.youtube.com/watch?v=mnDVjrt7xPA",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "OgPvZ8qCark",
    "title": "ניהול אמנים באחוזים או תשלום קבוע?",
    "youtubeUrl": "https://www.youtube.com/watch?v=OgPvZ8qCark",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "TCZUjBm6WRc",
    "title": "התפתחות המוזיקה ב-7 דקות | מ-בלוז וג׳אז עד EDM ומטאל – שיעור קצב מהיר עם עובד פינטו (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=TCZUjBm6WRc",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "dyCtx38OAQ8",
    "title": "איך לשבור את חוקי המשחק במוזיקה | מיתוסים על מפיקים, אולפנים, ציוד והצלחה – Yakir Cohen Productions",
    "youtubeUrl": "https://www.youtube.com/watch?v=dyCtx38OAQ8",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "VbwWkcc6His",
    "title": "אולפן הקלטות במודיעין | תקליטן לאירועים | סטודיו לצילום פודקאסטים | אטרקציות לאירועים 2025",
    "youtubeUrl": "https://www.youtube.com/watch?v=VbwWkcc6His",
    "tags": [
      "podcast",
      "dj-events",
      "studio-recording"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "podcast-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "vvEBQAjY7DA",
    "title": "חוזרים לגן פרק 2",
    "youtubeUrl": "https://www.youtube.com/watch?v=vvEBQAjY7DA",
    "tags": [
      "brand-tv"
    ],
    "services": [
      "podcast-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "DgstsJOo9z4",
    "title": "חוזרים לגן - פרק הבכורה - צפו בכוכבים חוזרים לגן ומתנהגים כמו ילדים. (כל חודש פרק!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=DgstsJOo9z4",
    "tags": [
      "brand-tv"
    ],
    "services": [
      "podcast-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "MeRi3plKf4Y",
    "title": "חוזרים לגן: סלבס בגן ילדים - הצצה לתוכנית הרשת החדשה עם בר ויקיר כהן",
    "youtubeUrl": "https://www.youtube.com/watch?v=MeRi3plKf4Y",
    "tags": [
      "brand-tv"
    ],
    "services": [
      "podcast-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "ik48Wyr_ypY",
    "title": "האח הגדול- איך זה נראה מבפנים? \"הפעמון\" תוכנית חדשה בהגשת יקיר כהן ויקיר איזמירלי (כל שבוע פרק חדש!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ik48Wyr_ypY",
    "tags": [
      "brand-tv",
      "education"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "u2WeBOR9Toc",
    "title": "זמן להכיר עם פרופסור אמיר חצרוני : פרובוקטור, פילוסוף, או פשוט איש כנה?",
    "youtubeUrl": "https://www.youtube.com/watch?v=u2WeBOR9Toc",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "AcRYGfFVGNM",
    "title": "זמן להכיר עם שראל וחושף: האמת על תעשיית המוזיקה היום!",
    "youtubeUrl": "https://www.youtube.com/watch?v=AcRYGfFVGNM",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "vOCL47gPB8w",
    "title": "זמן להכיר עם אורן חזן | השחיתות הגדולה בפוליטיקה, ההצעות, השליטה והמעצר של אשתו בשידור חי!",
    "youtubeUrl": "https://www.youtube.com/watch?v=vOCL47gPB8w",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "X4F7gG-uzWo",
    "title": "זמן להכיר עם יונתן ברק | מה חשב קטורזה על הסטאנדאפ? (הסרט החדש ועוד...)",
    "youtubeUrl": "https://www.youtube.com/watch?v=X4F7gG-uzWo",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "3H0rL-URX-g",
    "title": "זמן להכיר עם שרון בניפוסי מהאח הגדול | הדייט שהסתבך, סודות מהאח הגדול ועוד (כולל דייט הזוי ביותר!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=3H0rL-URX-g",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "M-7_h1NBZno",
    "title": "זמן להכיר עם נאווה בוקר | המסחרה בכנסת, איך עובדים עלינו עם הקול שלנו בקלפי והסוד שמעולם לא חשפה!",
    "youtubeUrl": "https://www.youtube.com/watch?v=M-7_h1NBZno",
    "tags": [
      "brand-tv",
      "podcast",
      "education"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "jBa06DNRXw0",
    "title": "זמן להכיר עם הרב יצחק בצרי | משיח, שדים, רוחות וכל מה שלא העזתם לשאול את המקובל! (מומלץ לצפות בלילה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=jBa06DNRXw0",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "SftLidFYjHU",
    "title": "זמן להכיר עם צחי נוי | יודלה (\"אסקימו לימון\") בחשיפה מטורפת על עולם המשחק!",
    "youtubeUrl": "https://www.youtube.com/watch?v=SftLidFYjHU",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "JW_PMcoafTA",
    "title": "זמן להכיר עם ננסי ברנדס | אחד האנשים המצחיקים שפגשתי בחיים.",
    "youtubeUrl": "https://www.youtube.com/watch?v=JW_PMcoafTA",
    "tags": [
      "entertainment",
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "Fs8iQJgQ5nA",
    "title": "זמן להכיר עם ניר בנילוש | המתיחה שעשינו על אופק מזרחי וכל האמת על הדמויות שלו (ראיון בלי פילטרים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Fs8iQJgQ5nA",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "TzI3ZvNrlPc",
    "title": "זמן להכיר עם דניאל יונה \"הסקילר\" מספר בפתיחות על האלימות מאמא שלו האהבה שנאה ברשת.",
    "youtubeUrl": "https://www.youtube.com/watch?v=TzI3ZvNrlPc",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "Kd5uU1qfoHk",
    "title": "זמן להכיר עם דורון מירן | הכל על האונס שעבר והקסם שיצא משליטה (פרק קורע מצחוק!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Kd5uU1qfoHk",
    "tags": [
      "entertainment",
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "w02utLTOhb4",
    "title": "זמן להכיר עם מתן גורודיש | האם העולם שטוח? (או צריך סיליקון)",
    "youtubeUrl": "https://www.youtube.com/watch?v=w02utLTOhb4",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "e1tX3g3jPrw",
    "title": "זמן להכיר עם ג'קו אייזנברג | כל הסודות נחשפים (ומה היה הסיפור עם שלמה ארצי?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=e1tX3g3jPrw",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "2YG-iVOrA3Q",
    "title": "זמן להכיר עם דניס צ׳רקוב | כל האמת מאחורי \"אמוזה\" (ראיון ראשון ובלעדי!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=2YG-iVOrA3Q",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "XwD3Y3lgnyM",
    "title": "זמן להכיר עם רגב הוד | האם רגב הוד יכול לקבל פיצה בחינם בגלל השם שלו?",
    "youtubeUrl": "https://www.youtube.com/watch?v=XwD3Y3lgnyM",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "YRNlfj2HJco",
    "title": "זמן להכיר עם קובי סוויסה KS | מה הקסם שלו והאם מדובר בדמות? (המותג כמו שלא הכרתם...)",
    "youtubeUrl": "https://www.youtube.com/watch?v=YRNlfj2HJco",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "Qp9RWZdWdAk",
    "title": "זמן להכיר עם השף ישראל אהרוני - איך הופכים פיתה עם שוקולד למנת גורמה.",
    "youtubeUrl": "https://www.youtube.com/watch?v=Qp9RWZdWdAk",
    "tags": [
      "brand-tv",
      "podcast",
      "education"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "GUfILyvp89c",
    "title": "זמן להכיר עם רון נשר | האמת של רון נשר בלי פילטרים ומסכות! (פרק 4)",
    "youtubeUrl": "https://www.youtube.com/watch?v=GUfILyvp89c",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "kg5LXKFxlpg",
    "title": "זמן להכיר עם גילי כהן | \"הפה של המדינה\" פותח על כולם ללא מעצורים! (פרק 3)",
    "youtubeUrl": "https://www.youtube.com/watch?v=kg5LXKFxlpg",
    "tags": [
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "SZkByV8XIA0",
    "title": "זמן להכיר עם אוהד בוזגלו | המודח הטרי מהישרדות אוהד בוזגלו בראיון מעניין ומצחיק בטירוף (פרק 2)",
    "youtubeUrl": "https://www.youtube.com/watch?v=SZkByV8XIA0",
    "tags": [
      "entertainment",
      "brand-tv",
      "podcast"
    ],
    "services": [
      "podcast-hub",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "uPAMD4Ua_08",
    "title": "זמן להכיר | מה גרם לפרופסור אמיר חצרוני לבכות באולפן ???? (פרק 1)",
    "youtubeUrl": "https://www.youtube.com/watch?v=uPAMD4Ua_08",
    "tags": [
      "brand-tv",
      "podcast",
      "studio-recording"
    ],
    "services": [
      "podcast-hub",
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "lmYykgKAdUg",
    "title": "תקליטן לחתונה מתחיל בהפרדה וממשיך רגיל (דתי לאומי) | איך זה באמת נראה מעמדת ה-DJ  (ללא פילטרים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=lmYykgKAdUg",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Z2HMKWDhH-A",
    "title": "איך להיות זמרת | האם כל אחד יכול להיות זמר? איך למצוא ייחודיות בקול שלנו (טיפים ממפיק)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Z2HMKWDhH-A",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "H2twwlmPZyA",
    "title": "איך לגרום לשיר שלי להצליח | האם כל שיר יכול להצליח? (בדקה על הצלחת שירים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=H2twwlmPZyA",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "eau6RKvtU30",
    "title": "להקים אולפן הקלטות מקצועי? | כמה כסף צריך? אם אתה מתכנן אחסוך לך אלפי שקלים! (הסבר בדקה בדיוק)",
    "youtubeUrl": "https://www.youtube.com/watch?v=eau6RKvtU30",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "_2fWZLeo2jo",
    "title": "חיקויים קורעים מצחוק של כל הזמרים הכי חזקים בישראל |שרים יובל המבולבל - חלק 2 (2021)",
    "youtubeUrl": "https://www.youtube.com/watch?v=_2fWZLeo2jo",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "B5wvK5x1i38",
    "title": "מיקסר אומנים מה זה? מיקסרים לאומנים - מה ההבדלים האמתיים בין החברות השונות? (באמת הסאונד מורגש?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=B5wvK5x1i38",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "1nRDZvjSMJo",
    "title": "בן זיני ומאור אדרי | שחקנית או שקרנית? (הגרסה הלא מצונזרת!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=1nRDZvjSMJo",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "hSGhpN_CR7s",
    "title": "קריינות DJ  - החשיבות של קריינות לסט שלכם וממי כן להזמין קריינות (ללא פילטרים סאונד מצלמה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=hSGhpN_CR7s",
    "tags": [
      "voiceover",
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "M6r7NzBiEpc",
    "title": "קליפ בת מצווה נערה אמתית | איך מקליטים ומצלמים קליפ לבת מצווה (מצחיק, מיוחד ומרגש!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=M6r7NzBiEpc",
    "tags": [
      "entertainment",
      "bat-bar-mitzvah",
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-gifts",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "1wuUFP18yzs",
    "title": "מה זה מיסופוניה? | רגישות פתאומית לרעשים? ולמה זה בכלל מעניין מפיקים? (אולפן הקלטות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=1wuUFP18yzs",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "oIv_9CPkIJM",
    "title": "Sync מה זה - DJ האם זו בושה לתקלט ולנגן עם כפתור הסינק? (סרטון לתקליטנים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=oIv_9CPkIJM",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "5ZUPV_F_IXk",
    "title": "מה ההבדל בין מונו לבין סטריו בדקה תבינו הכל",
    "youtubeUrl": "https://www.youtube.com/watch?v=5ZUPV_F_IXk",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "dXNajBkm2Ec",
    "title": "חתונה יהודית | תקליטן לחתונה  מהממת באוויר הפתוח בראשון לציון (הפתעה בסוף!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=dXNajBkm2Ec",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "oakie5I__y8",
    "title": "כמה עולה להביא זמר לאירוע? | הפדיחה שהגיעה אלינו לאולפן! מתוך חתונה אמתית!(לא להזמין כל זמר לאירוע!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=oakie5I__y8",
    "tags": [
      "dj-events",
      "education",
      "studio-recording"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Gdrs2H4THo8",
    "title": "אולפן הקלטות מחירים | כמה עולה להקליט שיר? יש מבצעים? מה ההבדלים במחירים? (הכי נכון שיש!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Gdrs2H4THo8",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "BGORA8bST3A",
    "title": "שיר בת מצווה מרגש | ילדה שרה שרה שיר לאביה ז\"ל מרגש בטירוף! כולל קליפ בת מצווה (אולפן הקלטות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=BGORA8bST3A",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "Ps8_MSOrc8Q",
    "title": "איך להפיק שיר אצלנו - מה המחיר להקליט שיר? (על מה לא לוותר!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Ps8_MSOrc8Q",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "y8w_BRwe_tg",
    "title": "דרשה לבר מצווה | קצר ולעניין - איך  מקליטים ילד ביישן ומגיעים לתוצאות מדהימות! (אולפן הקלטות לילדים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=y8w_BRwe_tg",
    "tags": [
      "bat-bar-mitzvah",
      "blessings",
      "education",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "mvfpz5hTa7E",
    "title": "איך מתגברים על מחסום כתיבה?",
    "youtubeUrl": "https://www.youtube.com/watch?v=mvfpz5hTa7E",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "oYUCREQDl28",
    "title": "קורס הפקה מוזיקלית | מה עדיף בית ספר או פרטי אחד על אחד? (מה ההבדל העיקרי?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=oYUCREQDl28",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "UnBc2a3ve9w",
    "title": "אולפן הקלטות הסודות | איך ניגשים לשיר? איך השיר שלכם ישמע טוב יותר? (הקלטת שיר חתונה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=UnBc2a3ve9w",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "n3TTJ44xefI",
    "title": "אולפן הקלטות זול | מה האמת מאחורי אולפן הקלטות זול ומהו ההפסד שלכם! (כמה עולה?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=n3TTJ44xefI",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "U3Rdp8uQHew",
    "title": "איך ואיפה לפרסם שיר שהקלטתי? ואיך שיר יכול באמת להצליח היום?",
    "youtubeUrl": "https://www.youtube.com/watch?v=U3Rdp8uQHew",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "6J705M1bHJI",
    "title": "תקליטן לבר מצווה היסטרית במיוחד! (פרסומת)",
    "youtubeUrl": "https://www.youtube.com/watch?v=6J705M1bHJI",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "RLTzgsRk1vk",
    "title": "אולפן הקלטות עם תיקון זיופים מטורף! | אחת ההקלטות הכי מצחיקות שעשינו (ספרו לנו מה דעתכם על התוצאה..)",
    "youtubeUrl": "https://www.youtube.com/watch?v=RLTzgsRk1vk",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "x1rBoKvYFHM",
    "title": "בר מצווה במלון | DJ במלון האוריאנט ירושלים (תקליטן לבר מצווה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=x1rBoKvYFHM",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "zIfu3KIR6Xk",
    "title": "ביבי נתניהו - אסתפר לבד (ביבי מסתפר עם המכונה של KS)",
    "youtubeUrl": "https://www.youtube.com/watch?v=zIfu3KIR6Xk",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "K8c9xAHWN-g",
    "title": "הקלטת שיר מקורי | איך מקליטים שיר מקורי? כל תהליך ההקלטה כולל הסבר עד לתוצר הסופי (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=K8c9xAHWN-g",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Z9LMW3nQJfw",
    "title": "הקלטת שיר מקורי | טיפ חשוב וכל מה שלא אמרו לכם על הכסף מאחורי ההקלטה..",
    "youtubeUrl": "https://www.youtube.com/watch?v=Z9LMW3nQJfw",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "vtyR6SEo5Y4",
    "title": "איזו תוכנת הפקה הכי טובה? קיובייס, אבלטון לייב, אדובי, פרוטי-לופס וכו'..",
    "youtubeUrl": "https://www.youtube.com/watch?v=vtyR6SEo5Y4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "jhQJoC55O-c",
    "title": "רעשים באולפן הקלטות?   למה יש לי רעש באולפן? ומה הפתרון ?! אני משתגעעע!!!",
    "youtubeUrl": "https://www.youtube.com/watch?v=jhQJoC55O-c",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "cKvQd08GWAk",
    "title": "לשיר מהבטן | שמעו איזה קול אפשר להפיק בשירה נכונה! (סופר מיוחד ומרגש!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cKvQd08GWAk",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "vhILhb04nDI",
    "title": "מה ההבדל בין מיקרופון דינמי למיקרופון קונדנסר? מה איכותי יותר? ולאיזה שימוש מתאים כל אחד? (48V)",
    "youtubeUrl": "https://www.youtube.com/watch?v=vhILhb04nDI",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Na8crRnhaNg",
    "title": "איזה קונטרולר הכי מומלץ לרכוש והאם באמת יש הבדלים בין החברות השונות כמו פיוניר ונייטיב וכו'...?",
    "youtubeUrl": "https://www.youtube.com/watch?v=Na8crRnhaNg",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "g8Kfb6QFRT0",
    "title": "Mp3 או Wav? מה איכותי יותר? אמפי 3 או WAV? על מה לשמור את השיר?",
    "youtubeUrl": "https://www.youtube.com/watch?v=g8Kfb6QFRT0",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "uSADHJreYdQ",
    "title": "איזה מיקרופון לקנות לסטודיו או אולפן הקלטות והאם יש מיקרופון זול וטוב?",
    "youtubeUrl": "https://www.youtube.com/watch?v=uSADHJreYdQ",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "TgwieFCKl2U",
    "title": "מיקס ומאסטרינג | למה להשקיע במיקס מאסטרינג אם בסוף שומעים את השיר בפלאפון",
    "youtubeUrl": "https://www.youtube.com/watch?v=TgwieFCKl2U",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "j9KaaiKebXU",
    "title": "סוגי מוניטורים לאולפן הקלטות ומה הכי כדאי? האם אפשר לעשות מיקס עם רמקולים של מחשב? (אתם תופתעו!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=j9KaaiKebXU",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "1comkUPPE94",
    "title": "אולפן הקלטות מחירים - אם תשירו כמו התימני הזה תקבלו הקלטה בחינם! (עריכה חדשה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=1comkUPPE94",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "SyF8hlGusDY",
    "title": "מיקס מאסטרינג | טעות לעבוד על ערוץ אחד! לא לעבוד בסולו!",
    "youtubeUrl": "https://www.youtube.com/watch?v=SyF8hlGusDY",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "4k_v9ARcAKw",
    "title": "מיקס לשיר | טעות נפוצה במיקס -  שתשנה לכם את היצירה המוזיקלית שלכם בעתיד.",
    "youtubeUrl": "https://www.youtube.com/watch?v=4k_v9ARcAKw",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "eLiuaf9Gi7Q",
    "title": "תקליטן לאירוע קטן - מתכננים אירוע בקרוב? הכל תחת קורת גג אחת! (וידאו עם סאונד מיוחד!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=eLiuaf9Gi7Q",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "XSrLicVCaGM",
    "title": "תקליטן טוב ומיוחד לאירועים מדהימים| לחשוב מחוץ לקופסא עם DJ יקיר כהן (עריכה מדהימה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=XSrLicVCaGM",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "r_SBaepTLsE",
    "title": "יובל דיין שרק תחייך - גרסת הסמים הלא מצונזרת (שרק תסתבך - לראות עד הסוף...)",
    "youtubeUrl": "https://www.youtube.com/watch?v=r_SBaepTLsE",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Aj1j4Km0V5s",
    "title": "בר צברי - ג'וני | פארודיה - ג'ינה הגרסה הנשית (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Aj1j4Km0V5s",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "7DEp-gnDTs4",
    "title": "קריינות DJ סט | איך די ג'יי ממתג את הסט שלו? קריין לסט DJ (ב10 שניות מיתוג)",
    "youtubeUrl": "https://www.youtube.com/watch?v=7DEp-gnDTs4",
    "tags": [
      "voiceover",
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "CSbxjVRelx8",
    "title": "לא תאמינו איך נראה אירוע ב\"לאגו\" ראשון לציון! | מתחיל בלי צנזורה...",
    "youtubeUrl": "https://www.youtube.com/watch?v=CSbxjVRelx8",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "zC0B9jwiIHY",
    "title": "DJ לחתונה | איך אתם נראים מהעיניים של הDJ?",
    "youtubeUrl": "https://www.youtube.com/watch?v=zC0B9jwiIHY",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Yw0oDKP9dkE",
    "title": "קורס DJ | איך להיות תקליטן? מה לומדים? איפה ואיך? (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Yw0oDKP9dkE",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "vs_IfmAJHSo",
    "title": "שפת גוף - איך לקרוא אנשים - הרצאה בבית ספר לאומנות הבמה (שפת גוף וכוחן של מילים רקע)",
    "youtubeUrl": "https://www.youtube.com/watch?v=vs_IfmAJHSo",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "d7IcHKUV2JI",
    "title": "קורס DJ פרטי 1X1 כל מה שלא יגידו לכם! | מה מיוחד בך? ומה מייחד אותך? פחד במה ועוד... (צפייה חינם!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=d7IcHKUV2JI",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "uVVa373jv40",
    "title": "איך נכנסים לחופה עם יקיר כהן? לפני שהחתן נכנס לחופה הדי ג'יי נתן לו 10 שניות להתחרט! (וידאו אמיתי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=uVVa373jv40",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "g1M9yOZdVGY",
    "title": "תקליטן ברסלב | DJ דתי - אירוע אמיתי! בלי פילטרים ובלי מסכות! (כולל מאחורי הקלעים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=g1M9yOZdVGY",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "Vuz4m8OaDcA",
    "title": "פתיח לסט DJ - שלושה תקליטנים יוצרים פתיחה לסט |  קריין DJ - איך עושים קריינות לתקליטן (דיג'יי סט)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Vuz4m8OaDcA",
    "tags": [
      "voiceover",
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "IB4hDHXx7Lg",
    "title": "לך עם האמת שלך עדן מאירי  - גרסת הטינדר (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=IB4hDHXx7Lg",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "sNZPrz-rasQ",
    "title": "הקלטת שיר חתונה - אולפן הקלטות לשיר חתונה - איך מקליטים שיר לחתונה? ואיך זה נראה ונשמע מהאירוע עצמו!",
    "youtubeUrl": "https://www.youtube.com/watch?v=sNZPrz-rasQ",
    "tags": [
      "dj-events",
      "education",
      "studio-recording"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ArRkxTRrdVk",
    "title": "אולפן הקלטות ברכה | הקלטה של ברכה מאולתרת זה באמת יצא משליטה.... אבא פותח על 200... (הכל מאולתר!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ArRkxTRrdVk",
    "tags": [
      "blessings",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "hJ6l8FQIRzI",
    "title": "תקליטן לאירועים - מהאוטו ועד לאולם כולל ראיון אישי מצחיק ומיוחד! (יום מצחיק בחייו של DJ)",
    "youtubeUrl": "https://www.youtube.com/watch?v=hJ6l8FQIRzI",
    "tags": [
      "entertainment",
      "dj-events"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "J2i9mmBZrig",
    "title": "יקיר כהן הפקות - עם איזה ציוד אנחנו עובדים? איך נראה האולפן שלנו?",
    "youtubeUrl": "https://www.youtube.com/watch?v=J2i9mmBZrig",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "GzYGwVfj_S0",
    "title": "איך עושים צלצול מיוחד לטלפון? ג'ינגל שמתקשרים עם מוזיקה שמחוברת ומזוהה לעסק שלכם! (מאחורי הקלעים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=GzYGwVfj_S0",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "FtzsXXnts_k",
    "title": "שמחה פרידמן - בקרוב (יתגדל ויתקדש) רמיקס אירועים (Simche Friedman Remix) רמיקס אירועים (יקיר כהן)",
    "youtubeUrl": "https://www.youtube.com/watch?v=FtzsXXnts_k",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "cqNudtRJFIM",
    "title": "למה זרקתי שני טרמפיסים מהאוטו ואיך הם קשורים לעופר לוי? (הופעה עופר לוי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cqNudtRJFIM",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "O2RHNRZCmZM",
    "title": "יקיר כהן קריין פרסומות מקצועי - האחים ממן הגיעו להקליט שיר ובסוף שמעו הקלטת קריינות... (מצחיק)",
    "youtubeUrl": "https://www.youtube.com/watch?v=O2RHNRZCmZM",
    "tags": [
      "entertainment",
      "voiceover"
    ],
    "services": [
      "studio-hub-entertainment",
      "voiceover-course"
    ]
  },
  {
    "videoId": "Z1QIgyMYMsk",
    "title": "אליעד נחום - מסע | גרסת הערסיות - עוד פרודיה מטורפת מבית יקיר כהן הפקות (ניר בנילוש)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Z1QIgyMYMsk",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "JzKnS0Crk0Y",
    "title": "אלעד לוי וליהי בנין - Save the Date | Forget The Date - לא תאמינו איך זה נשמע באירוע!",
    "youtubeUrl": "https://www.youtube.com/watch?v=JzKnS0Crk0Y",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "VaYJzpmR4yU",
    "title": "תקליטן לחתונה בטרויה - די ג'יי לחתונות רק יקיר כהן | (סרטון מהצלם חתונה של האירוע!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=VaYJzpmR4yU",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "Mh3RosX3a8g",
    "title": "תקליטנים בלבד! כניסה לתקליטנים שרוצים  קריין לסט - איך עושים קריינות לסט? מיועד לDJ בלבד! (איכות 4K)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Mh3RosX3a8g",
    "tags": [
      "voiceover",
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "y1LHYRx7teQ",
    "title": "מתן פרץ פרודיה \"הזוג הזה\" - גרסת הסטודנטים | לא סובל את המרצה הזה!  (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=y1LHYRx7teQ",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "QEi_ReWJaF0",
    "title": "תקליטן לבר מצווה - אולם \"אגמים\" - לקוחות הגיעו ליקיר רק מהיוטיוב... (צילום מזווית אחרת!!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=QEi_ReWJaF0",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "Fm6B3kOAPzI",
    "title": "תקליטן חובבן ותקליטן מקצוען חייבים לדעת! קורס DJ - על מה רוקד הקהל? איך לבחור גרסאות? (חלק 2 בחינם.)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Fm6B3kOAPzI",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "T02cTKffIzc",
    "title": "עדן חסון - כפיות פרודיה | גרסת השמנים (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=T02cTKffIzc",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "SkKzGBasSSk",
    "title": "קורס DJ חינם  - שיעור DJ מטורף וחשוב לכל תקליטן בארץ! (לילדה בת 10)",
    "youtubeUrl": "https://www.youtube.com/watch?v=SkKzGBasSSk",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ycpL0Korfew",
    "title": "כבד אותי - חולם להיות דודו פארוק? כבד אותי אחי ישראל מועלמי באולפן הקלטה (מאחורי הקלעים באולפן!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ycpL0Korfew",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ZAjiVXZsdEA",
    "title": "תקליטן דתי לאומי | ככה נראים אירועים של יקיר כהן DJ מיוחד לאירועים לא שיגרתים! (וידאו מאחורי הקלעים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ZAjiVXZsdEA",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "rcIcBMb1FL4",
    "title": "סולדי - הגרסה הישראלית Soldi 4K (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=rcIcBMb1FL4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "XBRa-EBwiqI",
    "title": "אין יותר מועדונים גרסת השמנים (יקיר כהן הפקות מארח את יוסי פנסו)",
    "youtubeUrl": "https://www.youtube.com/watch?v=XBRa-EBwiqI",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "cAUEetsX-mw",
    "title": "בקדושה ובטהרה - מה כלכך מסובך??? (הקלטת ברכת כלה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cAUEetsX-mw",
    "tags": [
      "blessings"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub"
    ]
  },
  {
    "videoId": "Yb6Se23Y0pc",
    "title": "הלהיט החדש של אלה שמקריחים (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Yb6Se23Y0pc",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "hzOHnLHN9lM",
    "title": "הקלטת שיר ותיקון זיופים לבת מצווה | אולפן הקלטות במרכז - ומעבר מנועה קירל ל- Mi Gente (היסטרי!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=hzOHnLHN9lM",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "Vbx2pzHmpBM",
    "title": "אייל גולן ובניה ברבי - ממה את מפחדת (פרודיה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Vbx2pzHmpBM",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "s2TeoC4YTy0",
    "title": "תקליטן לחתונה יקיר כהן | יקיר איזמירלי בחתונה הכי מצחיקה שעשיתי! (מאחורי הקלעים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=s2TeoC4YTy0",
    "tags": [
      "entertainment",
      "dj-events"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "t3GQFHrd7wk",
    "title": "הקלטת שיר קאבר באולפן הקלטות | איך זה באמת נראה שמגיעים פעם ראשונה לאולפן? (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=t3GQFHrd7wk",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Ll-lusc6zHM",
    "title": "קריינות לסט עם קטעים שקוראים לנו באירועים! בונוס: כמה תקליטן מרוויח בערב? (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Ll-lusc6zHM",
    "tags": [
      "voiceover",
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "RHfbCirXwn4",
    "title": "איך עושים להיט? על סמך מה שדר רדיו מחליט שהוא להיט מדינה? חשיפה: הסודות מהאולפן (יקיר כהן וגל רבינו)",
    "youtubeUrl": "https://www.youtube.com/watch?v=RHfbCirXwn4",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "yIqctNtrJRw",
    "title": "מתכון לחומוס - איך מכינים חומוס? חושף את המתכון הסודי! + ערב קריוקי לפנים! (djVlog 005)",
    "youtubeUrl": "https://www.youtube.com/watch?v=yIqctNtrJRw",
    "tags": [
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Rvu_z0GP_J0",
    "title": "תקליטן לחתונה בלי פילטרים! איך זה נראה מהצד של הדיג'יי? הרמוניה בגן (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Rvu_z0GP_J0",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "xzghVo3FTyk",
    "title": "המופע של אלעד לוי וליהי באולפן הקלטות - איך הקליטו את השיר לאבד שליטה? (כולל מתכון לפיצה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=xzghVo3FTyk",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "KugBlc_xfl0",
    "title": "אולפן להקליט שיר - הגשמת חלום לילדה שרוצה להקליט לכיף שלה! ואנחנו תמיד שמחים להקליט! (מצחיק!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=KugBlc_xfl0",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "nsHUwF9hc_U",
    "title": "צחי רבינא ופירחית איך עושים פארודיה? - פרודיה לשיר Taki Taki (מאחורי הקלעים באולפן הקלטות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=nsHUwF9hc_U",
    "tags": [
      "entertainment",
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "8em-2u988NM",
    "title": "אולפן הקלטות נגיש - עיוורת מקליטה שיר בפעם הראשונה בחייה! (יקיר כהן הפקות) - קורעעע!",
    "youtubeUrl": "https://www.youtube.com/watch?v=8em-2u988NM",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "0Xmv9ZnjGB8",
    "title": "אולפן הקלטות במרכז | מקליטים שיר עם הכוונה וכוונה למילים (בית ספר לדיקציה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=0Xmv9ZnjGB8",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "lG6GLK7Mqys",
    "title": "הקלטת ברכת כלה במרכז כל התהליך מהצחוקים בהתחלה עד הדמעות בסוף..!  (איך מקליטים ברכת כלה?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=lG6GLK7Mqys",
    "tags": [
      "blessings",
      "education"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "g6S2Qehb1qg",
    "title": "אולפן הקלטות - מקליטים ילדה קטנה לשיר מתנה - מאז שהיא הגיע היא לא הוציאה מילה.. עד ש... (קורע!!!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=g6S2Qehb1qg",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "PBmwYVdgWLw",
    "title": "מודה אני - שיר לבת מצווה אולפן הקלטה מקצועי במודיעין |  אני מיואש למות! (כולל המלצה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=PBmwYVdgWLw",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "qYiuRdBJMuE",
    "title": "פרסומת ברדיו | איך עושים פרסומת לרדיו? קריינות לתשדיר ברדיו יקיר כהן בלייב (אמיתי!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=qYiuRdBJMuE",
    "tags": [
      "voiceover",
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "RScxQ_D9OQ0",
    "title": "אולפן הקלטות עם סבלנות - להקלטת שיר - עד שתצא הנשמה... אני אסע לך....! (אימל'ה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=RScxQ_D9OQ0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "x2z667nSbTg",
    "title": "יונתן הקטן בתמנית - אולפן הקלטות בירושלים, מודיעין והמרכז (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=x2z667nSbTg",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "79trXZNWGgI",
    "title": "אולפן הקלטות והשרירים של אבי - מאחורי הקלעים כולל הכוונה ותיקון זיופים מצחיק (תוצאה של לפני ואחרי!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=79trXZNWGgI",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "qIDeNpsFHxM",
    "title": "אולפן הקלטות במודיעין - אין על תמנים...  (מישהו הבטיח לי...) מצחיק, קורע וכיף! תהנו...",
    "youtubeUrl": "https://www.youtube.com/watch?v=qIDeNpsFHxM",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "DYlVFFx7uxo",
    "title": "שיר צה\"ל קחו את המדים שהרסו לי את החיים - גרסת האמת \"יושב אני בין סורגים\" (יקיר כהן הפקות) - המקוצר.",
    "youtubeUrl": "https://www.youtube.com/watch?v=DYlVFFx7uxo",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "TPstgUTd-uI",
    "title": "תקליטן חתונה | לפני שתסגרו תקליטן לחתונה כדאי לכם לראות את זה... (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=TPstgUTd-uI",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "X1IO30Jsfqg",
    "title": "הקלטות לבת מצווה - אולפן הקלטות במרכז לדרשה לבת מצווה - מוטלת עלי החברה... (כמה אפשר להתבלבל בדרשה?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=X1IO30Jsfqg",
    "tags": [
      "bat-bar-mitzvah",
      "blessings",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "M-lKFCzrz5Y",
    "title": "אולפן הקלטות עם תיקון זיופים | מתחביביי...להפוך באמצע ההקלטות למורה לפיתוח קול! (כולל תוצר סופי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=M-lKFCzrz5Y",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ISHN-6gGUh0",
    "title": "תקליטן לבר מצווה - די ג'יי בר מצווה עם הזמר עוזיה צדוק (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ISHN-6gGUh0",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "tfhzouiiCAo",
    "title": "אולפן הקלטות במרכז - איך אומרים לזמר שהוא שר פח? (אחת ההקלטות ההזויות שהיו לנו!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=tfhzouiiCAo",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Jb4RYS0rGVA",
    "title": "אולפן הקלטות במודיעין - אמא מסתלבטת על הילדה שלה? (שאקירה התמניה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Jb4RYS0rGVA",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "csk0JTYlFpM",
    "title": "תקליטן לחתונה קהל מעורב (גם דתי וגם חילוני) תקליטים לקהלים מגוונים (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=csk0JTYlFpM",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "hg4u1GhrZ3Y",
    "title": "אולפן הקלטות במודיעין - הקלטת שיר בת מצווה של כל המשפחה (הבעיה שאסור לי לצחוק....)",
    "youtubeUrl": "https://www.youtube.com/watch?v=hg4u1GhrZ3Y",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "4uFnJgKF5ps",
    "title": "זיופים - התעלפתי מצחוק לא הצלחתי לעצור את עצמי, הקלטת שיר לחתונה עם מלא זיופים! (עם תוצר סופי מפתיע)",
    "youtubeUrl": "https://www.youtube.com/watch?v=4uFnJgKF5ps",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ckSu18zfGDc",
    "title": "מתופף אגדי על גוף של בנאדם מלא - מצחיק בטירוף! (חכו לסוף.. ממתינה לי שמה כאפה מצלצלת!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=ckSu18zfGDc",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "tf-WPot-x4w",
    "title": "עומר אדם הדלפה - מעריצה זועמת שרה על זה שכל הכרטיסים כל הזמן אוזלים! (יקיר כהן הפקות) פארודיה",
    "youtubeUrl": "https://www.youtube.com/watch?v=tf-WPot-x4w",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "gWXngwWrYjg",
    "title": "תקליטן בתל אביב - תקליטן לחתונה מומלץ במרכז  - לאירועים שמחים במיוחד! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=gWXngwWrYjg",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "sA7hp4SGK1o",
    "title": "חיקויים של פרשני חדשות |  רוני דניאל, ברהנו טגניה, משה נוסבאום וסיפורים הזויים ממש! (תגיבו אם דומה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=sA7hp4SGK1o",
    "tags": [
      "entertainment",
      "dj-events"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "bVUQCpthGhs",
    "title": "גלי צה\"ל - ראיון שחושף הכל על יקיר כהן - מה קרה שגלי צה\"ל פגשו את \"יקיר כהן הפקות\"?",
    "youtubeUrl": "https://www.youtube.com/watch?v=bVUQCpthGhs",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "cTs_ilxfLLk",
    "title": "תקליטן לבת מצווה - בסוף הערב הכי כיף לשחק עם הקהל! תקליטן לכל סוגי האירועים! (תקליטן ומנחה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cTs_ilxfLLk",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "h6FNvKRhrxc",
    "title": "חיקויים של זמרים - איזמירלי יסביר לכם מי הוא לא... תנו לו צ'אנס גרסה קורעת! (כל הזמרים בשיר אחד!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=h6FNvKRhrxc",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "uY871OUAjMM",
    "title": "תיקון זיופים - אם היא תשמע אותו לפני עריכה - הם לא התחתנו.... (תיקון זיופים אולפן הקלטות מודיעין)",
    "youtubeUrl": "https://www.youtube.com/watch?v=uY871OUAjMM",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "zpsjTKYhRYs",
    "title": "אני רואה שדים ב12 בלילה.... סיפור אמיתי! (14+)(מסכנים באו להקליט באולפן הקלטות ב12 בלילה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=zpsjTKYhRYs",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "7u6dviEF0ag",
    "title": "תיקון זיופים לשירים - אולפן הקלטות עם תיקון זיופים - הקלטת מתמחים בהקלטות שירי היפהופ. (יקיר כהן)",
    "youtubeUrl": "https://www.youtube.com/watch?v=7u6dviEF0ag",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "xID2V0BM_g0",
    "title": "פארודיה - מוקדש לכל המרוקאיות! (נכתב בדם..) מתכון מטבוחה קל לאוזניים ורגיש לסבתא (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=xID2V0BM_g0",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "6ij6aN1Xwh4",
    "title": "אנריקה אגלסיאס לגור בחור - לא קולטים שם רדיו (ככה זה לגור בחור!) מוקדש לבני ברק, פרדס חנה וכרכור!",
    "youtubeUrl": "https://www.youtube.com/watch?v=6ij6aN1Xwh4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "kImKQffedmI",
    "title": "תקליטן לאירועים - עוד אירוע מוצלח של יקיר כהן (מסיבת נשף סוף שנה) - הצצה למאחורי הקלעים בנשף.",
    "youtubeUrl": "https://www.youtube.com/watch?v=kImKQffedmI",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "k6aKm2MpL24",
    "title": "אולפן הקלטות במודיעין - יש אנשים שהשם שלהם פשוט לא מתאים להם... (מה מפריע ליקיר בשמות?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=k6aKm2MpL24",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "wZZbVqVRZN0",
    "title": "אולפן הקלטות מומלץ ומטורף - מקליט זמר עם 3 אצבעות ברגליים... למה? (מצחיק אש)",
    "youtubeUrl": "https://www.youtube.com/watch?v=wZZbVqVRZN0",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "FRYyZ-vkYw8",
    "title": "Shape Of You - ניר בנילוש גרסת הערסים (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=FRYyZ-vkYw8",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "OLxE-n0ZDeU",
    "title": "כל אחד יכול להיות זמר! - אולפן הקלטות הטוב ביותר בארץ! (תיקון זיופים מפתיע במיוחד!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=OLxE-n0ZDeU",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "U6LJERy6Wdk",
    "title": "איך עושים רמיקס? שקד קוממי אצל יקיר כהן - רמיקס פתיחת ריקודים מקורי! (יוצרים גרסה לאירועים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=U6LJERy6Wdk",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "no2r9mKhno0",
    "title": "אולפן הקלטות - לאתיופים של שמות של מותגים... (תיקון זיופים מושלם!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=no2r9mKhno0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "q8Lrs93jQHQ",
    "title": "עדן בן זקן - חיים שלי הגרסה הלא מצונזרת! | אתה כספומט שלי בת-אל ירמי (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=q8Lrs93jQHQ",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "u6njndCSrQY",
    "title": "עומר אדם - אוהבת אותי צמחוני \"את אוהבת אותי צמחוני לא עם בשר עם סלט יווני\" (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=u6njndCSrQY",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "-1Wre-ps7u8",
    "title": "קריין חדשות נופל לשטויות של יקיר להגיד בשידור חי \"יקיר המלך\" (מתוך חדשות גלי ישראל 106FM)",
    "youtubeUrl": "https://www.youtube.com/watch?v=-1Wre-ps7u8",
    "tags": [
      "voiceover"
    ],
    "services": [
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "HRrh5awGU14",
    "title": "בית הנייר - הגרסה הישראלית | ניר בנילוש בלה צ'או (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=HRrh5awGU14",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "14AKcu3jbVw",
    "title": "אלעד לוי וליהי בנין עושים שכונה באולפן של יקיר כהן - יקיר נבהל! (מצחיק כולל תיקון זיופים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=14AKcu3jbVw",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "SvdGNSFccjc",
    "title": "תקליטן מומלץ - תקליטן לחתונה מיוחד! מתחתנים? קבלו המלצה על תקליטן! (אחרי אירוע מטורף ללא מסננים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=SvdGNSFccjc",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "-858Wq2H7dM",
    "title": "ג'סטין ביבר המרוקאי Love Yourself - אמא שלי שונאת אותך והיא סבבה עם כולם! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=-858Wq2H7dM",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "sdPYfNRJhAY",
    "title": "הייתי בטוח שעושים פארודיה חדשה... עד שהכל יתפוצץ לי בפנים...! (הנקמה בדרך..)",
    "youtubeUrl": "https://www.youtube.com/watch?v=sdPYfNRJhAY",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "OMEyJKQuOtk",
    "title": "טיפים להקלטת שיר לבת מצווה | אולפן הקלטות במרכז 10 טיפים שיעזרו לכם.. (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=OMEyJKQuOtk",
    "tags": [
      "bat-bar-mitzvah",
      "education",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "9HCvBCl5oAw",
    "title": "תקליטן לחתונה בצפון (טופז על הים) - משמידים את עכו! ככה נראה יום של תקליטן לחתונה! (מהבוקר עד הערב!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=9HCvBCl5oAw",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "1b9Olw9WTx0",
    "title": "אולפן הקלטות בירושלים | הקלטת שיר וברכות בשיא המקצועיות - עלילות משפחת \"קאסה\" באולפן (מצחיק!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=1b9Olw9WTx0",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "R8h0Oja_SPw",
    "title": "קורס DJ לנוער | קורס די ג'יי פרטי - מזה להיות תקליטן? שיעור טיפים לדי גיי חינם! (הצצה לשיעור מתנה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=R8h0Oja_SPw",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "2aQSSnVNR3Y",
    "title": "הקלטת ברכות אולפן במודיעין | אני בחיים לא אגיד לגבר \"אני אוהב אותך\" ... (הצהרה שנויה במחלוקת)",
    "youtubeUrl": "https://www.youtube.com/watch?v=2aQSSnVNR3Y",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "5assO1pKLo0",
    "title": "יקיר כהן באירוע | די ג'יי מיוחד לאירוע מדהים! (בלוג מאחורי הקלעים של תקליטנים בירושלים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=5assO1pKLo0",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "8qYch1Kg0nQ",
    "title": "הקלטה באולפן הקלטות  - שהחתן מחליט להשתגע באולפן - הקלטת שיר לחתונה באולפן מקצועי ואיכותי! (קורע!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=8qYch1Kg0nQ",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "_mKLSDYUgLg",
    "title": "הקלטת שיר | הקלטת שיר באולפן הקלטות מקצועי  - איך אפשר שלא להתאהב בך?! (אולפן הקלטות בירושלים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=_mKLSDYUgLg",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "D3sX7Me4CGg",
    "title": "תקליטן לבר מצווה במודיעין | איך מוצאים תקליטן מיוחד לאירוע בר מצווה במודיעין (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=D3sX7Me4CGg",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah",
      "education"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "VlbiXwwrpdY",
    "title": "תעקוב אחרי זה יוסיף לך עוקבים... המלצה של ילד מתוקה עם הקלטה סופר מצחיקה וכייפית. (אולפן בירושלים)",
    "youtubeUrl": "https://www.youtube.com/watch?v=VlbiXwwrpdY",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "NDhZf0yy5_Q",
    "title": "אין לי בגרות - יקיר איזמירלי  | השיר שאסור להשמיע להורים! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=NDhZf0yy5_Q",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "fp2feAMCmhM",
    "title": "הדלפה!!! מסינגלים חדשים של עומר אדם, ליאור נרקיס, משה פרץ ועוד... ;) (חיקויים מדוייקים!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=fp2feAMCmhM",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "vsu2bR4Ugnk",
    "title": "תקליטן דתי לחתונה חסידית בבני ברק | די ג'יי לאירוע דתי חרדי - ציבור ספרדי ליטאי. (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=vsu2bR4Ugnk",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "6CWP425rgV0",
    "title": "אולפן הקלטות עם זמרת שחושפת - מה הסוד שכל הזמרים מסתירים מכם? מה הם באמת עושים לפני הקלטות? (2021)",
    "youtubeUrl": "https://www.youtube.com/watch?v=6CWP425rgV0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "9o_MUvYVZKw",
    "title": "מאז שיש לך חברה אתה כבר לא חבר - Wiz Khalifa - See You Again תייגו חבר שנעלם (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=9o_MUvYVZKw",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "y3G8gGzG0gE",
    "title": "תקליטן בר מצווה בירושלים | בר מצווה בירושלים ככה נראה תקליטן לבר מצווה! עם עוזיה צדוק! (בלוג)",
    "youtubeUrl": "https://www.youtube.com/watch?v=y3G8gGzG0gE",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "lV0-YMFquOM",
    "title": "איך אומרים \"בלייבק\" או \"פלייבק\"? הקול שלו מזכיר לי שילוב של סטטיק ועמיר בניון... (מצחיק עם תוצאה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=lV0-YMFquOM",
    "tags": [
      "entertainment",
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "7avikWMtRqg",
    "title": "לזהות גבר קמצן | ההמנון החדש של הקמצנים (ג'סטין ביבר)",
    "youtubeUrl": "https://www.youtube.com/watch?v=7avikWMtRqg",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Z5w1v5naEaY",
    "title": "איזו מוזיקה ילדים אוהבים? אולפן הקלטות לכניסה לבת מצווה + שאלון מהיר וכייפי! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Z5w1v5naEaY",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "BYmCtLGWmO8",
    "title": "תקליטן לאפטר | מה הנוער מסתיר במסיבות בית ספר? די ג'יי למסיבת סיום בית ספר (עם נוער מחולון)",
    "youtubeUrl": "https://www.youtube.com/watch?v=BYmCtLGWmO8",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "IhBW_P_PQHo",
    "title": "ניר בנילוש - \"לכי כפרה\" הגרסה של הערסים, הלהיט הבא של Shakira & Maluma -Chantaje (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=IhBW_P_PQHo",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "7y7IQPL8k9M",
    "title": "שיר במתנה לבר מצווה - הקלטה אישית באולפן מקצועי",
    "youtubeUrl": "https://www.youtube.com/watch?v=7y7IQPL8k9M",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "wfTY8Bz2uE4",
    "title": "הקלטת ברכה \"מרגשת עד דמעות\"... מצחיקה ומרגשת בו זמנית! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=wfTY8Bz2uE4",
    "tags": [
      "entertainment",
      "blessings"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "f73H6uLM6aE",
    "title": "יושב אני בין סורגים (כלא צבאי) - הסיפור האמיתי! חיילים בצבא האהבה! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=f73H6uLM6aE",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Sy9IMvgKKwM",
    "title": "כל האמת מאחורי \"דספסיטו\" ו- \"סואללה\" מתוך ראיון חושפני בגלי צה\"ל (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Sy9IMvgKKwM",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "1llizRSIx5s",
    "title": "איפה ניסו \"דספסיטו\" -הלהיט הספרדי עכשיו בגרסה המזרחית! חובה לשמוע Despacito (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=1llizRSIx5s",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "uscGOdmltFA",
    "title": "דודו אהרון נחשף באולפן! האמת על מה נכתב השיר שלו \"את אשתי\"? (הסוד שיקיר בטעות גילה לזוג שחיתן)",
    "youtubeUrl": "https://www.youtube.com/watch?v=uscGOdmltFA",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "ZL9UivG5eN0",
    "title": "חיקויים קורעים באולפן ההקלטות - שלמה ארצי, זוהר ארגוב, משה פרץ, אמיר בניון, ליאור נרקיס ועוד מלא!",
    "youtubeUrl": "https://www.youtube.com/watch?v=ZL9UivG5eN0",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "OixEalmqjQk",
    "title": "תיקון פיץ' מקצועי - לפני ואחרי שדרוג קולי מלא",
    "youtubeUrl": "https://www.youtube.com/watch?v=OixEalmqjQk",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "SvhfZK9Ribg",
    "title": "שקד קוממי באולפן  - כיכר המדינה רמיקס  (בואו לגלות איך יוצרים רמיקס חתונות?)",
    "youtubeUrl": "https://www.youtube.com/watch?v=SvhfZK9Ribg",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "aRRxHg9C26U",
    "title": "תקליטן לפורים | מסיבות פורים עם DJ מטורף יראו וישמעו טוב יותר! (בלוג קורע במיוחד של יקיר כהן!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=aRRxHg9C26U",
    "tags": [
      "entertainment",
      "dj-events"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "4ucGwLUyan8",
    "title": "תקליטן דתי בירושלים - די ג'יי חתונה דתית מטורפת במיוחד! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=4ucGwLUyan8",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "grgkgxRuvX0",
    "title": "אולפן הקלטות לבת מצווה - עד שהיא תשיר היא כבר תתחתן.... (בת 12 חייבת דעה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=grgkgxRuvX0",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "cE5lO58mW_4",
    "title": "ניר בנילוש -  חייל משמר הגבול (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=cE5lO58mW_4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "rBwtACnVHcU",
    "title": "אולפן הקלטות בירושלים - תיקון זיופים מדהים שמעו בעצמכם.. (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=rBwtACnVHcU",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "rcn_NesSnx4",
    "title": "Ed Sheeran - Shape Of You [Israel Cover Video] - שייפ אוף יו (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=rcn_NesSnx4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "e4yPUoDVu_w",
    "title": "אולפן הקלטות מודיעין והסביבה - הרסה את הקול שלה מהסיגריות (כולל לפני תיקון ואחרי תיקון) מדהים!!!",
    "youtubeUrl": "https://www.youtube.com/watch?v=e4yPUoDVu_w",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "lWkZtMrUcxg",
    "title": "מתיחה על פיני - אבא של חמימו מהאח הגדול 8 - גילי מיילי ויקיר כהן (מצחיק למות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=lWkZtMrUcxg",
    "tags": [
      "entertainment",
      "brand-tv"
    ],
    "services": [
      "podcast-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "wQtdGYj_zkU",
    "title": "חיקויים- פרשני חדשות | רוני דניאל, ברהנו טגניה, משה נוסבאום  (הבחור הזה קורע במיוחד..!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=wQtdGYj_zkU",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "T-wnuEM7aMw",
    "title": "חיקויים- פרשני ערוץ הספורט! אלי אוחנה, מודי בר און, אבי מלר, רון קופמן, נדב יעקובי, שגיא כהן ועוד...",
    "youtubeUrl": "https://www.youtube.com/watch?v=T-wnuEM7aMw",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "RtAiHRFzx9U",
    "title": "קליפ ושיר לבת מצווה - מודה אני גרסת בנות כולל תיקון זיופים וקליפ (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=RtAiHRFzx9U",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "lCIoEuxBm7A",
    "title": "איך מקליטים ילדה קטנה באולפן? אולפן הקלטות במודיעין (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=lCIoEuxBm7A",
    "tags": [
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "OQskf68WCoY",
    "title": "חיקויים של כל הזמרים המוכשרים והטובים בארץ! סרטון חיקויים כזה עוד לא ראיתם... (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=OQskf68WCoY",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "H70FfIx9rtY",
    "title": "מה עושים כשילד מתחצף באולפן? (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=H70FfIx9rtY",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "Pd1l6-RlXqQ",
    "title": "כיוון מצחיק לילדה בהקלטת שיר באולפן (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Pd1l6-RlXqQ",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "KYAah8VSNg8",
    "title": "לתקן זיופים באולפן הקלטות? הקלטת שיר בר מצווה - איך זה נראה שעובדים? (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=KYAah8VSNg8",
    "tags": [
      "bat-bar-mitzvah",
      "education",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "Tcv7Tb1uCfI",
    "title": "קריינות מקצועית באולפן - כך נשמע ההבדל באיכות שידור",
    "youtubeUrl": "https://www.youtube.com/watch?v=Tcv7Tb1uCfI",
    "tags": [
      "voiceover",
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "hC2GgTt_cmo",
    "title": "שיר וקליפ לבת מצווה-(יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=hC2GgTt_cmo",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "_9RptmDKS1Y",
    "title": "אולפני הקלטה ברחובות - \"תורה ועבודה ויאללה בלאגן!\" (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=_9RptmDKS1Y",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "j27ONz3RrS0",
    "title": "מרביץ ליקיר כהן באולפן ההקלטות! (הקטע המלא בלי עריכה!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=j27ONz3RrS0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "63R17iIWrTM",
    "title": "כמה זמן להקליט דרשה!? בואו לצפות מאחורי הקלעים \"כמה זמן מקליטים דרשה\" ומה באמת קורה בתוך האולפן.",
    "youtubeUrl": "https://www.youtube.com/watch?v=63R17iIWrTM",
    "tags": [
      "blessings",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "k5Z5TIlreAY",
    "title": "אולפן הקלטות מאחורי הקלעים | מה אתם לא רואים שאנשים מגיעים להקליט שיר? (מצחיק על דמעות!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=k5Z5TIlreAY",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "BtVwYDug3W8",
    "title": "\"יונתן הקטן\" בתמנית - מישהו אחר היה בועט אותנו (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=BtVwYDug3W8",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "19v-LGKWiqY",
    "title": "הקלטת שיר - אולפן הקלטות בירושלים - מישהוווווו אחד הקרועים :) (מאחורי הקלעים הקטע המלא!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=19v-LGKWiqY",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "wN4N0QsfDJo",
    "title": "קורס קריינות - אחד על אחד - תוך כדי עבודה (יקיר כהן הפקות) קריינות לסט",
    "youtubeUrl": "https://www.youtube.com/watch?v=wN4N0QsfDJo",
    "tags": [
      "voiceover",
      "education"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "voiceover-course",
      "voiceover-hub",
      "voiceover-services"
    ]
  },
  {
    "videoId": "DFAd4BjYCQU",
    "title": "שירים חסידיים קצביים לחתונה - סט חדש ומקפיץ במיוחד! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=DFAd4BjYCQU",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "jbrcnLjn6kk",
    "title": "אולפן הקלטות בירושלים - ילדה בת 6 מצחיקה בטירוף! (יקיר כהן הפקות כבר לא מתפקד..)",
    "youtubeUrl": "https://www.youtube.com/watch?v=jbrcnLjn6kk",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "qY67kRGsRnY",
    "title": "ברכת כלה - וידאו מאולפן עם הכלה, איך עושים ואיך זה נשמע בסוף מרגש ממש! (ליווי אישי מההתחלה ועד הסוף)",
    "youtubeUrl": "https://www.youtube.com/watch?v=qY67kRGsRnY",
    "tags": [
      "blessings",
      "education",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "DX_VKlHp8IM",
    "title": "מקליטים באולפן - חיקוי של עומר אדם, לירן דנינו ומתן גלילוב (מצחיק בטירוף!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=DX_VKlHp8IM",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "Djl7sxQjbXk",
    "title": "אולפן הקלטות במודיעין - מקליטים שיר לילדה בת 9 שקצת מתפרעת... (ילדה צורחת באולפן!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=Djl7sxQjbXk",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "V--5QihK8kg",
    "title": "DJ תקליטן ומתופף מקצועי לאירוע שלכם! איך זה נראה באמת מהעמדה של הDJ - קטע מטורף ממצלמה חצופה!",
    "youtubeUrl": "https://www.youtube.com/watch?v=V--5QihK8kg",
    "tags": [
      "dj-events",
      "education"
    ],
    "services": [
      "events-dj",
      "events-hub",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "EN8ojm_jGjE",
    "title": "חתונה הגרסה החרדית | ככה אירועים חרדים נראים שיודעים לגעת בכל העולמות! (יקיר כהן תקליטן דתי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=EN8ojm_jGjE",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "T-otXbppZMA",
    "title": "הקלטת שיר בת מצווה - האם הגזמתי בהסבר? ומה גרם לי להיקרע מצחוק! (אולפן הקלטות כייפי במרכז)",
    "youtubeUrl": "https://www.youtube.com/watch?v=T-otXbppZMA",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "m6BoG9ZfG6s",
    "title": "הקלטות באולפן בירושלים - עומר אדם יהיה בשוק מהילדה הזו! (אמא החליטה שהיא בורחת באמצע...) LIVE",
    "youtubeUrl": "https://www.youtube.com/watch?v=m6BoG9ZfG6s",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "HjTc8_LD7-w",
    "title": "הקלטות באולפן בירושלים - פסגת זאב, נווה יעקוב ושכונות ירושלים שימו לב! (יש כאן וידוי של השכונה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=HjTc8_LD7-w",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "02F0dsG2-V0",
    "title": "הקלטת ילד קטן -  אולפן הקלטות בירשולים (ככה מקליטים ילד מתוק בלי פילטרים בשידור חי!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=02F0dsG2-V0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "xvvwltogsk0",
    "title": "אנחנו רוצים לאכול חזיר באולפן -  אבל הקדוש ברוך הוא אמר שאסור!",
    "youtubeUrl": "https://www.youtube.com/watch?v=xvvwltogsk0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "GkqM6ZvgjiA",
    "title": "הקלטת שיר בת מצווה - אבא החליט שהוא זמר קורע מצחוק עד דמעות! (בשעות הקטנות של הלילה מצחיק)",
    "youtubeUrl": "https://www.youtube.com/watch?v=GkqM6ZvgjiA",
    "tags": [
      "entertainment",
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-gifts",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "iPLLWvcvpR4",
    "title": "בית ספר לידה - הקלטת שיר לבית ספר (כל התהליך עד התוצאה המושלמת!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=iPLLWvcvpR4",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "tjght9acNtE",
    "title": "אולפן הקלטות בירושלים - הצצה בלעדית איך מקליטים שיר בר מצווה? (מצחיק עם תוצאות מפתיעות במיוחד!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=tjght9acNtE",
    "tags": [
      "entertainment",
      "bat-bar-mitzvah",
      "education",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-gifts",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "TGKBqHswS_I",
    "title": "אולפן הקלטות בירושלים - שיר בת מצווה (לאן שלא תלכי) - הרבה אמת היה באולפן...",
    "youtubeUrl": "https://www.youtube.com/watch?v=TGKBqHswS_I",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "6RnF9SB9n6w",
    "title": "אולפן הקלטות בירושלים - הכי חשוב לא להיבהל מאחורי הקלעים של הקלטת שיר בת מצווה (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=6RnF9SB9n6w",
    "tags": [
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "recording-studio",
      "studio-gifts",
      "studio-hub"
    ]
  },
  {
    "videoId": "57FuI0EC_I4",
    "title": "פתיח לDj - קריינות לסט 2 קריינים עושים קריינות סופר מיוחדת לסט DJ (מאחורי הקלעים מצחיק!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=57FuI0EC_I4",
    "tags": [
      "entertainment",
      "voiceover",
      "dj-events"
    ],
    "services": [
      "studio-hub-entertainment",
      "voiceover-course"
    ]
  },
  {
    "videoId": "-u8m9kVFL04",
    "title": "הקלטת ברכות אולפן בירושלים - אמא מאיימת על אבא באולפן - \"משה חכה, חכה בבית...\"  (קורע!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=-u8m9kVFL04",
    "tags": [
      "entertainment",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "vr8TVTmPsrI",
    "title": "אלפן הקלטות ברחובות - מה קורה שנתקעים על מילה ולא מצליחים להקליט אותה באולפן הקלטות? (וידאו לייב)",
    "youtubeUrl": "https://www.youtube.com/watch?v=vr8TVTmPsrI",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "5-PTfYMMlV4",
    "title": "DJ Yakir Cohen Ft. Orr Shemesh Official Remix - Lo Mevina by Boomerang | \"לא היא לא מבינה\"",
    "youtubeUrl": "https://www.youtube.com/watch?v=5-PTfYMMlV4",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "HXrv5XwSuTo",
    "title": "עדן כהן - ביום הזה (קאבר מרגש)",
    "youtubeUrl": "https://www.youtube.com/watch?v=HXrv5XwSuTo",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "fr4t0MfZVZ0",
    "title": "שירים חסידיים קצביים לחתונה - סט מיוחד ומקפיץ! (יקיר כהן הפקות)",
    "youtubeUrl": "https://www.youtube.com/watch?v=fr4t0MfZVZ0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "y7qdj5ElN00",
    "title": "אולפן הקלטות בירושלים - ילדת בת מצווה מקליטה \"ילדה שלנו חמה\" למה חמה?!!?!? (מצחיק רצח)",
    "youtubeUrl": "https://www.youtube.com/watch?v=y7qdj5ElN00",
    "tags": [
      "entertainment",
      "bat-bar-mitzvah",
      "studio-recording"
    ],
    "services": [
      "recording-studio",
      "studio-gifts",
      "studio-hub",
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "wVLVfYFAVys",
    "title": "שיר בת מצווה |  היום נרקוד, היום נשיר, היום נשמח - מותר לגנוב ולקחת מילים ולחן. (רעיון שיר בת מצווה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=wVLVfYFAVys",
    "tags": [
      "bat-bar-mitzvah"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-video-clip",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "SgoAVkFSyDs",
    "title": "שיר לאמא במרוקאית מרגש בגרסה חדישה ופחות כבדה. תהנו! (2015)",
    "youtubeUrl": "https://www.youtube.com/watch?v=SgoAVkFSyDs",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "NA3Z54Bl-xM",
    "title": "די ג'יי יקיר כהן - תקליטן לחתונה ואירועים בלתי נשכחים",
    "youtubeUrl": "https://www.youtube.com/watch?v=NA3Z54Bl-xM",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "KzmhWvM8EEM",
    "title": "תקליטן לבר מצווה באולמי הבריאה - דרשה שילד עושה סטנדאפ (כולל כתיבה והכוונה)",
    "youtubeUrl": "https://www.youtube.com/watch?v=KzmhWvM8EEM",
    "tags": [
      "dj-events",
      "bat-bar-mitzvah",
      "blessings"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "blessings-video-clip",
      "events-dj",
      "events-hub",
      "recording-song-modiin",
      "studio-gifts"
    ]
  },
  {
    "videoId": "DviFRbn_nJU",
    "title": "סט מזרחית (לאוטו) חדש! השירים שיעשו לכם את היום (לשמיעה מיידית)",
    "youtubeUrl": "https://www.youtube.com/watch?v=DviFRbn_nJU",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "YS4fwVHSBAg",
    "title": "סט מזרחית (לאוטו) עם כל הלהיטים והשירים שיעשו לכם את היום (לעוד סטים הירשמו לערוץ)",
    "youtubeUrl": "https://www.youtube.com/watch?v=YS4fwVHSBAg",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "FD-oQ0v3DN0",
    "title": "מתיחה על נער חרמן | רונית החרמנית יוצאת לדרך עם שיחה סופר לא נורמלית (תקופת הצבא)",
    "youtubeUrl": "https://www.youtube.com/watch?v=FD-oQ0v3DN0",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "iA4dUB0jqK0",
    "title": "סט מזרחית (לאוטו) - DJ Yakir Cohen השירים הכי יפים לאוטו (אם עובד לכם זכיתם!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=iA4dUB0jqK0",
    "tags": [
      "dj-events"
    ],
    "services": [
      "events-dj",
      "events-hub"
    ]
  },
  {
    "videoId": "t8GUQiM8BqY",
    "title": "מתיחה על 144 בזק - איזה פאדיחה שכחתי את פרטי המתיחה (אבל עדיין מצחיק בטירוף - אני עם האלחוטי)",
    "youtubeUrl": "https://www.youtube.com/watch?v=t8GUQiM8BqY",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  },
  {
    "videoId": "NxCH17cXqaA",
    "title": "שירן מזרחי - רק בתפילה (2005) (שיר דיכאון מהמם!)",
    "youtubeUrl": "https://www.youtube.com/watch?v=NxCH17cXqaA",
    "tags": [
      "studio-recording"
    ],
    "services": [
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "kLA-XVH3m4E",
    "title": "שיר כניסה לחופה - ברכת כלה מוקלטת באולפן מקצועי",
    "youtubeUrl": "https://www.youtube.com/watch?v=kLA-XVH3m4E",
    "tags": [
      "blessings",
      "studio-recording"
    ],
    "services": [
      "blessings-bar-mitzvah",
      "blessings-bride-groom",
      "blessings-hub",
      "recording-song-modiin",
      "recording-studio",
      "studio-hub"
    ]
  },
  {
    "videoId": "z4ImC9HOVrI",
    "title": "אייל גולן (פארודיה) כשאת איתו Eyal Golan - צלצול מצחיק",
    "youtubeUrl": "https://www.youtube.com/watch?v=z4ImC9HOVrI",
    "tags": [
      "entertainment"
    ],
    "services": [
      "studio-hub-entertainment"
    ]
  }
] as const;

export const PORTFOLIO_CATALOG_COUNT = 272 as const;
