/** Hebrew labels for URL path segments (fallback when no service registry match). */
export const BREADCRUMB_SEGMENT_LABELS: Record<string, string> = {
  studio: "אולפן",
  podcast: "פודקאסט",
  events: "אירועים",
  attractions: "אטרקציות",
  equipment: "הגברה וציוד",
  video: "וידאו",
  photography: "צילום",
  voiceover: "קריינות",
  academy: "אקדמיה",
  online: "שירותים אונליין",
  "vocal-fix": "תיקון ווקאלי",
  business: "עסקים",
  "social-media": "ניהול סושיאל",
  "reel-factory": "מפעל רילס לספקים",
  blog: "בלוג",
  about: "אודות",
  contact: "צור קשר",
  book: "הזמנה מקוונת",
  courses: "קורסים",
  clinic: "מרפאה",
  stuttering: "גמגום",
  voucher: "שובר מתנה",
  privacy: "מדיניות פרטיות",
  terms: "תנאי שימוש",
  accessibility: "נגישות",
  blessings: "ברכות",
  "dj-events": "תקליטן לאירועים",
  "stage-led-dj": "עמדת LED לתקליטן",
  "wedding-attractions-packages": "חבילות אטרקציות לחתונה",
  "photo-slideshow": "מצגת תמונות",
  "podcast-recording": "צילום והקלטת פודקאסט",
  "podcast-production": "הפקת פודקאסט מא׳ עד ת׳",
  "podcast-editing": "עריכת פודקאסט",
  "podcast-studio": "אולפן פודקאסט",
  "podcast-studio-modiin": "סטודיו במודיעין",
  "podcast-with-grandpa": "פודקאסט עם סבא וסבתא",
  "mobile-podcast-at-home": "פודקאסט נייד",
  "mobile-studio": "אולפן נייד",
  "recording-studio": "אולפן הקלטות",
  "recording-song-modiin": "הקלטת שיר במודיעין",
  "studio-jerusalem": "אולפן לירושלים",
  "corporate-video": "וידאו עסקי",
  "event-filming": "צילום אירועים",
  presentation: "מצגות",
  faq: "שאלות נפוצות",
  pricing: "מחירון",
  gifts: "מתנות והקלטות",
  "funny-ringtone": "רינגטון מצחיק",
  host: "הנחיית אירועים",
  jerusalem: "ירושלים",
  cities: "ערים",
  "content-studio": "סושיאל דאמפ, רילז באולפן",
  "on-site-studio": "אולפן זמני בחברה",
  "corporate-songs": "שירים לחברות",
  audiobooks: "ספרי שמע",
  "audio-branding": "מיתוג קולי",
  "legacy-digitization": "החייאת זיכרונות",
  transcription: "תמלול וכתוביות",
  "voice-cloning": "שיבוט קול",
  workshops: "סדנאות לצוותים",
  "employer-branding": "תוכן HR וקליטה",
  "self-service-studio": "אולפן שירות עצמי",
  "online-ai-pricing": "מחירון AI",
  "send-file": "שליחת קובץ",
  mixing: "מיקס",
  "photo-enhance": "שיפור תמונה",
  "pitch-correction": "תיקון טון",
  "ai-music": "מוזיקה ב-AI",
  "home-studio": "ייעוץ אקוסטיקה ובניית אולפן",
  "private-lessons": "שיעורים פרטיים",
  ulpan: "לימוד עברית",
  "dj-course": "קורס DJ",
  "music-production": "הפקת מוזיקה",
  "stuttering-course": "קורס גמגום",
  "bubble-machine": "מכונת בועות",
  "smoke-bubble-machine-events": "בועות ועשן",
  "cold-fireworks": "זיקוקי קור",
  "confetti-cannon": "תותח קונפטי",
  "giant-balloons": "בלונים ענקיים",
  "wedding-smoking-machine": "עשן לחתונה",
  "heavy-smoke-large-events": "עשן לאירועים גדולים",
  "smoke-cannons-for-events": "תותחי עשן",
  "singer-amplification": "הגברה לזמרים",
  wedding: "חתונה",
  services: "שירותים",
  course: "קורס",
  "bar-mitzvah": "בר/בת מצווה",
  "bat-mitzvah-clip": "קליפ בת מצווה",
  "video-clip": "שיר + קליפ",
  "bride-groom-blessing": "ברכת חתן וכלה",
  shop: "חנות",
  portfolio: "תיק עבודות",
  start: "מה קורה אחרי שפונים",
  "thank-you": "אישור הזמנה",
};

/** Exact path label when segment fallbacks are not enough. */
export const BREADCRUMB_PATH_OVERRIDES: Record<string, string> = {
  "/about/faq": "שאלות נפוצות",
  "/podcast/faq": "שאלות נפוצות - פודקאסט",
  "/dj-events/cities/jerusalem": "תקליטן בירושלים",
  "/studio/recording-song-modiin/gifts": "מתנות והקלטות",
  "/studio/recording-song-modiin/gifts/funny-ringtone": "רינגטון מצחיק במתנה",
  "/studio/blessings/bat-mitzvah-clip": "קליפ בת מצווה",
};
