"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils";

/* ─── Pagefind runtime types ────────────────────────────────────────────────── */

interface PFResult {
  url: string;
  meta: { title?: string; image?: string };
  excerpt: string;
}

interface PFApi {
  search: (
    query: string,
  ) => Promise<{ results: Array<{ id: string; data: () => Promise<PFResult> }> }>;
}

declare global {
  interface Window {
    pagefind?: PFApi;
  }
}

/* ─── Props ─────────────────────────────────────────────────────────────────── */

type Props = {
  placeholder?: string;
  className?: string;
  maxResults?: number;
};

/* ─── Component ─────────────────────────────────────────────────────────────── */

export default function SiteSearch({
  placeholder = "חיפוש באתר...",
  className,
  maxResults = 7,
}: Props) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<PFResult[]>([]);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const timerRef = useRef<ReturnType<typeof setTimeout>>(undefined);
  const loadedRef = useRef(false);

  /* Load Pagefind from /public/pagefind/ — generated by `npm run index:search`.
     The Function constructor prevents bundlers from trying to resolve this path. */
  const initPagefind = useCallback(async () => {
    if (loadedRef.current || window.pagefind) {
      loadedRef.current = true;
      return;
    }
    try {
      // eslint-disable-next-line @typescript-eslint/no-implied-eval
      const pf: PFApi = await new Function(
        "path",
        "return import(path)",
      )("/pagefind/pagefind.js");
      window.pagefind = pf;
      loadedRef.current = true;
    } catch {
      // Not yet built — silently no-op in dev
    }
  }, []);

  const runSearch = useCallback(
    async (q: string) => {
      if (!q.trim() || !window.pagefind) {
        setResults([]);
        return;
      }
      setLoading(true);
      try {
        const res = await window.pagefind.search(q);
        const data = await Promise.all(
          res.results.slice(0, maxResults).map((r) => r.data()),
        );
        setResults(data);
      } catch {
        setResults([]);
      } finally {
        setLoading(false);
      }
    },
    [maxResults],
  );

  /* Debounce search by 220ms */
  useEffect(() => {
    clearTimeout(timerRef.current);
    if (query.trim()) {
      timerRef.current = setTimeout(() => runSearch(query), 220);
    }
    return () => clearTimeout(timerRef.current);
  }, [query, runSearch]);

  /* Close dropdown on outside click / Escape */
  useEffect(() => {
    const onPointerDown = (e: PointerEvent) => {
      if (!containerRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("pointerdown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("pointerdown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, []);

  const showDropdown = open && query.trim().length > 0;

  return (
    <div ref={containerRef} dir="rtl" className={cn("relative w-full", className)}>
      {/* ── Input ── */}
      <div className="relative">
        {/* Search icon */}
        <svg
          className="pointer-events-none absolute start-3 top-1/2 -translate-y-1/2 text-[#1A1A1A]/35"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          aria-hidden
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>

        <input
          type="search"
          value={query}
          onChange={(e) => {
            const value = e.target.value;
            setQuery(value);
            setOpen(true);
            if (!value.trim()) {
              setResults([]);
            }
          }}
          onFocus={() => {
            setOpen(true);
            initPagefind();
          }}
          placeholder={placeholder}
          aria-label={placeholder}
          aria-autocomplete="list"
          aria-expanded={showDropdown}
          aria-controls="site-search-results"
          className={cn(
            "w-full rounded-xl border border-[#1A1A1A]/10 bg-[#FAFAF8]",
            "py-2.5 pe-4 ps-9 text-sm text-[#1A1A1A] placeholder:text-[#1A1A1A]/35",
            "outline-none transition-[border-color,box-shadow] duration-150",
            "focus:border-[#D42B2B] focus:ring-2 focus:ring-[#D42B2B]/15",
          )}
        />

        {/* Spinner */}
        {loading && (
          <span
            className="pointer-events-none absolute end-3 top-1/2 -translate-y-1/2"
            aria-hidden
          >
            <svg
              className="h-4 w-4 animate-spin text-[#D42B2B]"
              viewBox="0 0 24 24"
              fill="none"
            >
              <circle
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="3"
                className="opacity-20"
              />
              <path
                d="M12 2a10 10 0 0 1 10 10"
                stroke="currentColor"
                strokeWidth="3"
                strokeLinecap="round"
              />
            </svg>
          </span>
        )}
      </div>

      {/* ── Dropdown ── */}
      {showDropdown && (
        <ul
          id="site-search-results"
          role="listbox"
          aria-label="תוצאות חיפוש"
          className={cn(
            "absolute start-0 top-full z-50 mt-1.5 w-full overflow-hidden",
            "rounded-xl border border-[#1A1A1A]/8 bg-[#FAFAF8]",
            "shadow-[0_8px_32px_rgba(0,0,0,0.09)]",
          )}
        >
          {results.length > 0
            ? results.map((result) => (
                <li key={result.url} role="option" aria-selected={false}>
                  <Link
                    href={result.url}
                    onClick={() => {
                      setOpen(false);
                      setQuery("");
                    }}
                    className="group flex flex-col gap-1 border-b border-[#1A1A1A]/6 px-4 py-3 last:border-b-0 hover:bg-[#1A1A1A]/[0.03]"
                  >
                    <span className="text-sm font-semibold text-[#1A1A1A] transition-colors group-hover:text-[#D42B2B]">
                      {result.meta?.title ?? result.url}
                    </span>
                    {result.excerpt ? (
                      <span
                        className="line-clamp-2 text-xs leading-relaxed text-[#1A1A1A]/50"
                        /* Pagefind wraps matches in <mark> — safe HTML from its own index */
                        dangerouslySetInnerHTML={{ __html: result.excerpt }}
                      />
                    ) : null}
                  </Link>
                </li>
              ))
            : !loading && (
                <li className="px-4 py-3 text-sm text-[#1A1A1A]/45">
                  לא נמצאו תוצאות עבור &ldquo;{query}&rdquo;
                </li>
              )}
        </ul>
      )}
    </div>
  );
}
