/**
 * Legacy URL redirects (301 via next.config).
 *
 * SEO policy:
 * - **Active indexable pages** live only at canonical paths (see sitemap.ts).
 * - Redirects here are for **old inbound URLs** (Google Sites, analytics) or
 *   **true duplicates** - never to replace a page that should rank on its own.
 * - Do not add redirects between two URLs that both have full content.
 */

import { CANONICAL_REDIRECTS } from "./site-architecture";

export type LegacyRedirect = {
  source: string;
  destination: string;
  permanent: true;
};

/** Map legacy path canonical path (before prefix rules) */
const LEGACY_PATH_MAP: Record<string, string> = {
  /** Google Sites / קישורים ישנים - דף הבית הקנוני הוא `/` בלבד */
  "/home": "/",
  "/home/": "/",
  "/recording": "/studio",
  "/studio-main": "/studio",
  "/online-studio": "/online",
  "/podcast-pricing": "/podcast",
  "/recording-studio": "/studio/recording-studio",
  "/studio-recording": "/studio/recording-studio",
  "/studio/blessings/studio-blessings": "/studio/blessings",
  "/studio/mobile-studio/home-phone-blessings": "/studio/blessings#home-recording",
  "/stuttering-treatment": "/clinic",
  "/stuttering-therapy": "/stuttering",
  "/academy-music": "/academy",
  "/academy/stuttering-course": "/stuttering",
  "/bride-blessing": "/studio/blessings",
  "/groom-blessing": "/studio/blessings",
  "/photo-slider": "/photo-slideshow",
  "/podcast/podcast-studio/modiin-podcast-studio": "/podcast/podcast-studio-modiin",
  "/podcast/podcast-pricing": "/podcast",
  "/contact/whatsapp": "/contact",
  "/order": "/book",
  "/booking": "/book",
  "/book-studio": "/book",
  "/studio-booking": "/book",
  "/price": "/pricing",
  "/prices": "/pricing",
  "/pricing-page": "/pricing",
  "/מחירון": "/pricing",
  "/faq": "/about/faq",
  "/questions": "/about/faq",
  "/שאלות-נפוצות": "/about/faq",
  "/shop": "/voucher",
  "/online/online-pricing": "/online/online-ai-pricing",
  "/academy/ai-music": "/academy/dj-course",
  "/academy/ai-music.html": "/academy/dj-course",
  "/gift-card": "/voucher",
  "/gift-voucher": "/voucher",
  "/orders": "/voucher",
  "/voice-over": "/voiceover",
  "/for-business": "/business",
  "/dj-events": "/events/dj-events",
  "/wedding-songs": "/blog/wedding-songs-chuppah",
  "/weddings-songs": "/blog/wedding-songs-chuppah",
  "/chupa": "/blog/wedding-songs-chuppah",
  "/chuppa": "/blog/wedding-songs-chuppah",
  "/bride": "/blog/wedding-songs-chuppah",
  "/groom": "/blog/wedding-songs-chuppah",
  "/wedding": "/blog/wedding-songs-chuppah",
  "/weddings": "/blog/wedding-songs-chuppah",
  "/חתונה": "/blog/wedding-songs-chuppah",
  "/כלה": "/blog/wedding-songs-chuppah",
  "/חתן": "/blog/wedding-songs-chuppah",
  "/שירים-לחתונה": "/blog/wedding-songs-chuppah",
  "/שיר-כניסה-לחופה": "/blog/wedding-songs-chuppah",
  "/שירים-לבת-מצווה-2": "/blog/wedding-song-2026",
  "/bride-groom-blessing": "/studio/blessings/bride-groom-blessing",
  "/bar-mitzvah-clip": "/studio/blessings/video-clip",
  "/video/bar-mitzvah-clip": "/studio/blessings/video-clip",
};

/**
 * WordPress/WooCommerce migration redirects.
 * The site migrated from WP+WooCommerce to Next.js - these catch all the
 * old URL patterns that Google had indexed under the previous platform.
 */
const WORDPRESS_PATTERNS: Array<{ source: string; destination: string }> = [
  { source: "/product/:path*",           destination: "/voucher" },
  { source: "/product-tag/:path*",       destination: "/" },
  { source: "/product-category/:path*",  destination: "/" },
  { source: "/category/:path*",          destination: "/" },
  { source: "/tag/:path*",               destination: "/blog" },
  { source: "/shop-2/:path*",            destination: "/voucher" },
  { source: "/2019/:path*",              destination: "/blog" },
  { source: "/2020/:path*",              destination: "/blog" },
  { source: "/2021/:path*",              destination: "/blog" },
  { source: "/2022/:path*",              destination: "/blog" },
  { source: "/privacy-policy/:path*",    destination: "/privacy" },
  { source: "/privacy-policy",           destination: "/privacy" },
  { source: "/wp-admin/:path*",          destination: "/" },
  { source: "/wp-content/:path*",        destination: "/" },
  { source: "/wp-json/:path*",           destination: "/" },
  { source: "/xmlrpc.php",              destination: "/" },
  { source: "/feed",                     destination: "/blog" },
  { source: "/feed/:path*",              destination: "/blog" },
  { source: "/author/:path*",            destination: "/about" },
  { source: "/page/:path*",              destination: "/blog" },
  { source: "/2018/:path*",              destination: "/blog" },
  { source: "/2017/:path*",              destination: "/blog" },
  { source: "/2023/:path*",              destination: "/blog" },
  { source: "/2024/:path*",              destination: "/blog" },
  { source: "/index.aspx",               destination: "/" },
  { source: "/main.asp",                 destination: "/" },
];

/** Hebrew-slug service pages from the old WordPress site */
const HEBREW_SERVICE_SLUGS: Record<string, string> = {
  // DJ & Events
  "/תקליטן-לחתונה": "/events/dj-events",
  "/תקליטן-לחתונה-בירושלים": "/dj-events/cities/jerusalem",
  "/תקליטן-לחתונה-מומלץ": "/events/dj-events",
  "/תקליטן-לחתונות": "/events/dj-events",
  "/תקליטן-לאירועים": "/events/dj-events",
  "/תקליטן-לאירועים-2": "/events/dj-events",
  "/תקליטן-לאירוע-קטן-חתונה-דתית-יום-הולדת": "/events/dj-events",
  "/תקליטן-דתי": "/events/dj-events",
  "/תקליטן-דתי-לבר-מצווה": "/events/dj-events",
  "/תקליטן-בר-מצווה": "/events/dj-events",
  "/תקליטן-ומפעיל-לבר-מצווה": "/events/dj-events",
  "/תקליטן-חתונות": "/events/dj-events",
  "/תקליטן-מבצע": "/events/dj-events",
  "/תקליטן-טוב": "/events/dj-events",
  "/תקליטן-מהצפון": "/events/dj-events",
  "/תקליטן-בדרום": "/events/dj-events",
  "/תקליטן": "/events/dj-events",
  "/תקליטנים-לחתונה": "/events/dj-events",
  "/תקליטנים-בירושלים": "/dj-events/cities/jerusalem",
  "/תקליטן-בירושלים": "/dj-events/cities/jerusalem",
  "/תקליטן-דתי-לחתונה-בירושלים": "/dj-events/cities/jerusalem",
  "/תקליטן-לחינה-בירושלים": "/dj-events/cities/jerusalem",
  "/תקליטן-באשדוד": "/events/dj-events",
  "/תקליטן-באילת": "/events/dj-events",
  "/תקליטן-בבאר-שבע": "/events/dj-events",
  "/תקליטן-בבית-שמש": "/events/dj-events",
  "/תקליטן-בגבעתיים": "/events/dj-events",
  "/תקליטן-בהוד-השרון": "/events/dj-events",
  "/תקליטן-בהרצליה": "/events/dj-events",
  "/תקליטן-ביהוד": "/events/dj-events",
  "/תקליטן-בחולון": "/events/dj-events",
  "/תקליטן-בחיפה": "/events/dj-events",
  "/תקליטן-בטבריה": "/events/dj-events",
  "/תקליטן-בקרית-גת": "/events/dj-events",
  "/תקליטן-בקרית-אונו": "/events/dj-events",
  "/תקליטן-בערד": "/events/dj-events",
  "/תקליטן-בפתח-תקווה": "/events/dj-events",
  "/תקליטן-ברעננה": "/events/dj-events",
  "/תקליטן-בתל-אביב": "/events/dj-events",
  "/תקליטן-לחינה": "/events/dj-events",
  "/תקליטן-לבר-מצווה-במרכז": "/events/dj-events",
  "/תקליטן-מומלץ": "/events/dj-events",
  "/דיגיי-חתונה": "/events/dj-events",
  "/dj-בחתונה": "/events/dj-events",
  "/dj-דתי": "/events/dj-events",
  "/dj-לאירוע": "/events/dj-events",
  "/dj-לאירועים": "/events/dj-events",
  "/די-גיי-לחתונה": "/events/dj-events",
  "/די-גיי-לחתונות": "/events/dj-events",
  "/די-גיי-לחתונה-דתית": "/events/dj-events",
  "/די-גיי-לאירועים": "/events/dj-events",
  "/די-גיי-טוב": "/events/dj-events",
  "/די-ג-יי-לחתונה": "/events/dj-events",
  "/מחיר-תקליטן-כמה-עולה-להזמין-תקליטן": "/events/dj-events",
  "/מחיר-תקליטן-לחתונה": "/events/dj-events",
  "/איך-בוחרים-תקליטן-לחתונה": "/events/dj-events",
  "/מנחה-לאירועים": "/events/host",
  "/הגברה-לאירועים": "/events/equipment/singer-amplification",
  "/ציוד-הגברה-לתקליטנים": "/events/equipment",
  "/השכרת-ציוד-הגברה-לאירועים": "/events/equipment",
  "/תופים-לחתונה": "/events/dj-events",
  "/אטרקציות-לחתונה": "/events/attractions",
  "/אטרקציות-לאירוע-הכי-יפות-איכותיות-ובמ": "/events/attractions",
  "/אטרקציות-לבר-מצווה": "/events/attractions",
  "/אטרקציות-לחתונה-לרחבה": "/events/attractions",
  "/גימיקים-לחתונה": "/events/attractions",
  "/הפתעות-לרחבה": "/events/attractions",
  "/חבילת-אטרקציות-לחתונה": "/events/wedding-attractions-packages",
  "/ארגון-חתונה": "/events",
  "/אירגון-חתונה": "/events",
  "/מה-צריך-לחתונה": "/events",
  "/מה-כדאי-לעשות-בחתונה": "/events",
  "/אירוע-באולם-קטן-בירושלים": "/events",
  "/מעגלי-מתופפים-באירועים": "/events",
  "/תאורה-למסיבות-מה-אתם-חייבים-לדעת-על-תו": "/events",
  "/השכרת-תאורה-למסיבות-בירושלים": "/events",
  "/אולמות-אירועים-מומלצים-בירושלים": "/dj-events/cities/jerusalem",
  "/אולמות-אירועים-בירושלים": "/dj-events/cities/jerusalem",
  // Smoke & effects
  "/מכונת-עשן": "/events/attractions/wedding-smoking-machine",
  "/עשן-כבד-לחתונה": "/events/attractions/wedding-smoking-machine",
  "/עשן-לסלואו": "/events/attractions/wedding-smoking-machine",
  "/עשן-קרח-יבש": "/events/attractions/wedding-smoking-machine",
  "/עשן-כבד-משטח-ענן": "/events/attractions/heavy-smoke-large-events",
  "/מכונת-בועות-סבון-עשן-שירות-הפעלה-לאירו": "/events/attractions/bubble-machine",
  "/תותחי-עשן-לאירועים-ולחתונה": "/events/attractions/smoke-cannons-for-events",
  "/רובה-עשן-ותותחי-קור-לאירועים": "/events/attractions/smoke-cannons-for-events",
  "/רובה-עשן-לאירועים": "/events/attractions/smoke-cannons-for-events",
  "/תותח-קונפטי-לאירועים": "/events/attractions/confetti-cannon",
  "/בלוני-ענק-לאירועים": "/events/attractions/giant-balloons",
  "/בלוני-לד-לאירועים": "/events/attractions/giant-balloons",
  "/בלוני-אורז-ברחבת-הריקודים": "/events/attractions/giant-balloons",
  "/בלונים-לאירועים": "/events/attractions/giant-balloons",
  "/בלונים-מתפוצצים-בסלואו": "/events/attractions/giant-balloons",
  "/סידור-בלונים-לאירוע": "/events/attractions/giant-balloons",
  "/מתקנים-מתנפחים": "/events/attractions/giant-balloons",
  "/בועות-סבון": "/events/attractions/bubble-machine",
  "/מכונת-בועות-סבון-לאירועים": "/events/attractions/bubble-machine",
  "/בועות-סבון-לחתונה": "/events/attractions/bubble-machine",
  "/זיקוקים-קרים-לחופה": "/events/attractions/cold-fireworks",
  "/זיקוקים-לחופה": "/events/attractions/cold-fireworks",
  "/זיקוקים-בטיחותי": "/events/attractions/cold-fireworks",
  "/זיקוקים-פירוטכניקה-לחתונה-מה-זה-כולל-ומאיפה": "/events/attractions/cold-fireworks",
  "/פירוטכניקה-לחתונה-מה-זה-כולל-ומאיפה": "/events/attractions/cold-fireworks",
  "/קרח-יבש-לאירועים": "/events/attractions",
  "/קרח-יבש-לחתונה": "/events/attractions",
  "/עמדת-לד-לאירוע-מתאים-גם-לdj": "/events/stage-led-dj",
  // Studio & Recording
  "/אולפן-הקלטות-במודיעין": "/studio",
  "/studiomodiindati": "/studio",
  "/אולפן-הקלטות-זול": "/studio",
  "/אולפן-הקלטות-מחירים": "/studio/pricing",
  "/כמה-עולה-שעת-אולפן": "/studio/pricing",
  "/אולפן-הקלטות-בירושלים": "/studio/studio-jerusalem",
  "/אולפן-הקלטות-2": "/studio",
  "/אולפן-הקלטות-באילת": "/studio",
  "/אולפן-הקלטות-באלעד": "/studio",
  "/אולפן-הקלטות-ביתי": "/academy/home-studio",
  "/אולפן-הקלטות-בלוד": "/studio",
  "/אולפן-הקלטות-בנס-ציונה": "/studio",
  "/אולפן-הקלטות-בראשון": "/studio",
  "/אולפן-הקלטות-בראשון-לציון": "/studio",
  "/אולפן-הקלטות-ברחובות": "/studio/studio-rehovot",
  "/אולפן-הקלטות-ברמלה": "/studio",
  "/אולפן-הקלטות-בשוהם": "/studio/studio-shoham",
  "/אולפן-הקלטות-בשילת": "/studio",
  "/אולפן-הקלטות-בירושלים-מחירים": "/studio/studio-jerusalem",
  "/להקים-אולפן-הקלטות": "/academy/home-studio",
  "/תכנון-אולפן-ביתי-מדריך-5-צעדים": "/academy/home-studio",
  "/הקלטת-שיר-חתונה": "/studio/recording-song-modiin",
  "/הקלטת-שיר-בר-מצווה": "/studio/recording-song-modiin",
  "/הקלטת-ברכות-לאירוע": "/studio/blessings",
  "/הקלטת-ברכות-באולפן-הקלטות-חוויה-מקצ": "/studio/blessings",
  "/הקלטת-דרשה-לבר-מצווה": "/studio/blessings/bar-mitzvah",
  "/דרשה-לבר-מצווה-קצר-ולעניין": "/studio/blessings/bar-mitzvah",
  "/קליפ-בת-מצווה": "/studio/blessings/bat-mitzvah-clip",
  "/סרטוני-בת-מצווה": "/studio/blessings/bat-mitzvah-clip",
  "/סרטון-קליפ-לבת-מצווה-הפקה-מרגשת-תוך-24-ש": "/studio/blessings/bat-mitzvah-clip",
  "/קליפ-לחתונה-חתן-שר-שיר-לכלה-ומכניס-אות": "/studio/blessings/video-clip",
  "/מיקס-ומאסטרינג": "/online/mixing",
  "/מיקס-מאסטרינג": "/online/mixing",
  "/מיקס-לשיר": "/online/mixing",
  "/מאסטרינג-וההפקה-המוזיקלית": "/online/mixing",
  "/תיקון-זיופים": "/online/vocal-fix",
  "/תיקון-זיופים-בקיובייס": "/online/vocal-fix",
  "/שחזור-שמע-דיגיטלי": "/online/vocal-fix",
  "/שיפור-איכות-הקלטה": "/online/vocal-fix",
  "/הפקת-שיר-מקורי": "/studio/recording-song-modiin",
  "/הפקת-שיר-מקורי-ai": "/studio/recording-song-modiin",
  "/הפקת-שיר-מחיר": "/studio/recording-song-modiin",
  "/שיר-מקורי": "/studio/recording-song-modiin",
  "/כמה-עולה-להיות-זמר": "/studio/recording-song-modiin",
  "/הפקה-מוזיקלית": "/academy/music-production",
  "/מפיק-מוזיקלי-האיש-מאחורי-הקלעים-של-כ": "/academy/music-production",
  "/רמיקס-לאירועים": "/academy/music-production",
  "/מיתוג-לדיגיי-אומן": "/business/professional-voiceover",
  "/סטודיו-לצילום": "/photography",
  // Voiceover & Branding
  "/קריינות": "/voiceover",
  "/קריינות-מקצועית": "/voiceover",
  "/קריין-מקצועי": "/voiceover",
  "/קריין-פרסומות": "/voiceover",
  "/קריינות-פרסומות": "/voiceover",
  "/קריינות-בחינם-ל-dj": "/business/professional-voiceover",
  "/קריינות-ל-dj": "/business/professional-voiceover",
  "/קריינות-לדי-גיי": "/business/professional-voiceover",
  "/קריינות-dj-והזמנה": "/business/professional-voiceover",
  "/קריינות-למרכזיה": "/business/professional-voiceover",
  "/קריינות-למרכזיה-2": "/business/professional-voiceover",
  "/קריינות-לרדיו": "/voiceover",
  "/קריין-חדשות": "/voiceover",
  "/שירותי-קריינות": "/voiceover",
  "/הזמנת-קריינות-בעברית": "/voiceover",
  "/קריינות-סרטי-תדמית-והדרכה": "/voiceover",
  "/קריינות-בעברית": "/voiceover",
  "/קריינות-חינם-ספירה-לאחור-dj-סילבסטר": "/business/professional-voiceover",
  "/קריינות-רדיו-וטיפים-לקריין-המתחיל-או-ל": "/voiceover",
  "/מיתוג-קולי-לעסק": "/business/professional-voiceover",
  "/גינגל": "/business/professional-voiceover",
  "/פרסומת-ברדיו": "/business/professional-voiceover",
  "/הקלטת-נתב-שיחות-מקצועי": "/business/professional-voiceover",
  // Academy & Courses
  "/קורס-קריינות": "/academy/voiceover",
  "/קורס-קריינות-אונליין-מחיר": "/academy/voiceover",
  "/קורס-קריינות-רדיו": "/academy/voiceover",
  "/קורסים-ל-djs": "/academy/dj-course",
  "/קורס-די-גיי-המדריך-המלא-איך-להפוך-תשוק": "/academy/dj-course",
  "/קורס-הפקה-מוזיקלית": "/academy/music-production",
  "/מדריך-לדי-גיי-המתחיל-כל-מה-שחשוב-לדעת-ל": "/academy/dj-course",
  "/איך-לשבור-את-חוקי-המשחק-במוזיקה-מיתוסי": "/academy/dj-course",
  "/רוצה-לעשות-פודקאסט-עם-רון-נשר": "/podcast/podcast-with-grandpa",
  // General / About
  "/ממליצים-עלינו": "/about",
  "/האמנים-שלנו": "/about",
  "/המלצות-djs": "/about",
  "/reviews": "/about",
  "/מי": "/about",
  "/about-us": "/about",
  "/about-us/": "/about",
  "/who-we-are": "/about",
  "/\\+6": "/contact",
  // Old portfolio pages
  "/דניאל-יונה": "/portfolio",
  "/גקו-אייזנברג": "/portfolio",
  "/ניר-בנילוש": "/portfolio",
  "/אוהד-בוזגלו": "/portfolio",
  "/רגב-הוד": "/portfolio",
  "/צחי-נוי": "/portfolio",
  "/גילי-כהן": "/portfolio",
  "/יקיר-איזמירלי": "/portfolio",
  "/ישראל-אהרוני": "/portfolio",
  "/ליאור-מיארה": "/portfolio",
  "/אמיר-חצרוני": "/portfolio",
  "/דורון-מירן": "/portfolio",
  "/דניס-צרקוב": "/portfolio",
  "/דניס-צ׳רקוב": "/portfolio",
};

/** Old English slugs used before the current route structure */
const OLD_ENGLISH_SLUGS: Record<string, string> = {
  "/bubble-machine": "/events/attractions/bubble-machine",
  "/confetti-cannon": "/events/attractions/confetti-cannon",
  "/cold-fireworks": "/events/attractions/cold-fireworks",
  "/stage-led-dj": "/events/stage-led-dj",
  "/wedding-smoking-machine": "/events/attractions/wedding-smoking-machine",
  "/smoke-bubble-machine-events": "/events/attractions/bubble-machine",
  "/giant-balloons": "/events/attractions/giant-balloons",
  "/foam-cannon": "/events/attractions/bubble-machine",
  "/smoke-gun": "/events/attractions/smoke-cannons-for-events",
  "/colored-smoke": "/events/attractions/smoke-cannons-for-events",
  "/dry-ice-events": "/events/attractions",
  "/recording-song-modiin": "/studio/recording-song-modiin",
  "/podcast-studio-modiin": "/podcast/podcast-studio-modiin",
  "/studio-jerusalem": "/studio/studio-jerusalem",
  "/studio-shoham": "/studio/studio-shoham",
  "/studio-rehovot": "/studio/studio-rehovot",
  "/gifts": "/studio/recording-song-modiin/gifts",
  "/wedding-attractions-packages": "/events/wedding-attractions-packages",
  "/music-production": "/academy/music-production",
  "/vocal-fix": "/online/vocal-fix",
  "/professional-voiceover": "/business/professional-voiceover",
  "/corporate-voiceover": "/business/professional-voiceover",
  "/dj-voiceover": "/business/professional-voiceover",
  "/dj-drops": "/business/professional-voiceover",
  "/home-studio": "/academy/home-studio",
  "/mixing": "/online/mixing",
  "/equipment": "/events/equipment",
  "/video/wedding": "/video/event-filming",
  "/online/pitch-correction": "/online/vocal-fix",
  "/online/audio-repair": "/online/vocal-fix",
  "/services/mixing-mastering": "/online/mixing",
  "/podcast-ron-nesher": "/podcast/podcast-with-grandpa",
  "/original-gift-for-grandpa": "/podcast/podcast-with-grandpa",
  "/link-to-clip-package": "/studio/blessings/video-clip",
  "/link-to-experience-package": "/book",
  "/dj-events/cities": "/events/dj-events",
  "/course-filming": "/academy",
  "/standup": "/events/host",
};

/** /attractions/* /events/attractions/* (with specific overrides) */
const ATTRACTIONS_OVERRIDES: Record<string, string> = {
  "/attractions": "/events/attractions",
  "/attractions/wedding-photography": "/photography/wedding",
  "/attractions/Wedding-photography": "/photography/wedding",
  "/attractions/event-attractions-pricing": "/events/attractions",
  "/attractions/heavy-smoke-large-events":
    "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events",
  "/attractions/wedding-smoking-machine/heavy-smoke-large-events":
    "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events",
  "/attractions/smoke-bubble-machine-events":
    "/events/attractions/bubble-machine/smoke-bubble-machine-events",
  "/attractions/bubble-machine/smoke-bubble-machine-events":
    "/events/attractions/bubble-machine/smoke-bubble-machine-events",
  "/attractions/attractions2026": "/events/attractions",
  "/attractions/wedding-smoking-machine":
    "/events/attractions/wedding-smoking-machine",
  "/attractions/bubble-machine": "/events/attractions/bubble-machine",
  "/attractions/cold-fireworks": "/events/attractions/cold-fireworks",
  "/attractions/confetti-cannon": "/events/attractions/confetti-cannon",
  "/attractions/giant-balloons": "/events/attractions/giant-balloons",
  "/attractions/led-booth": "/events/stage-led-dj",
  "/attractions/stage-led-dj": "/events/stage-led-dj",
  "/events/attractions/led-booth": "/events/stage-led-dj",
  "/events/led-booth": "/events/stage-led-dj",
  "/attractions/smoke-cannons-for-events":
    "/events/attractions/smoke-cannons-for-events",
};

function toRedirect(source: string, destination: string): LegacyRedirect {
  return { source, destination, permanent: true as const };
}

export function getLegacyRedirects(): LegacyRedirect[] {
  const fromMap = Object.entries(LEGACY_PATH_MAP).map(([source, destination]) =>
    toRedirect(source, destination),
  );

  const fromCanonical = Object.entries(CANONICAL_REDIRECTS).map(
    ([source, destination]) => toRedirect(source, destination),
  );

  const fromAttractions = Object.entries(ATTRACTIONS_OVERRIDES).map(
    ([source, destination]) => toRedirect(source, destination),
  );

  const fromHebrewSlugs = Object.entries(HEBREW_SERVICE_SLUGS).map(
    ([source, destination]) => toRedirect(source, destination),
  );

  const fromOldEnglishSlugs = Object.entries(OLD_ENGLISH_SLUGS).map(
    ([source, destination]) => toRedirect(source, destination),
  );

  const fromWordpressPatterns: LegacyRedirect[] = WORDPRESS_PATTERNS.map(
    ({ source, destination }) => ({ source, destination, permanent: true as const }),
  );

  /** Catch-all: any other /attractions/:path /events/attractions/:path */
  const attractionsCatchAll = toRedirect(
    "/attractions/:path*",
    "/events/attractions/:path*",
  );

  return [
    ...fromWordpressPatterns,
    ...fromMap,
    ...fromHebrewSlugs,
    ...fromOldEnglishSlugs,
    ...fromCanonical,
    ...fromAttractions,
    attractionsCatchAll,
  ];
}
