/**
 * Contextual internal links (max 2-3 per page) - edit here when adding routes.
 * Rendered by ContextualIntroParagraph; anchor text stays natural Hebrew.
 */

export type IntroSegment =
  | { type: "text"; value: string }
  | { type: "link"; href: string; label: string };

export const PAGE_INTRO_SEGMENTS: Partial<Record<string, IntroSegment[]>> = {
  "/events": [
    { type: "text", value: "הפקה מלאה לאירוע - DJ, הגברה, הנחיית קהל וניהול לו\"ז. לזוגות מתכננים חתונה - " },
    { type: "link", href: "/for-couples", label: "מסלול לזוגות" },
    { type: "text", value: ". לחתונה עם אטרקציות חובה ראו " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: ", למנחה מקצועי - " },
    { type: "link", href: "/events/host", label: "הנחיית אירועים" },
    { type: "text", value: "." },
  ],
  "/podcast": [
    { type: "text", value: "מגיעים לאולפן, מקליטים, ויוצאים עם פרק מוכן. לעריכה שוטפת לחברות - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". לפרק בודד: " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ", לשכירת חדר - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-recording": [
    { type: "text", value: "הפתרון המלא כולל צילום, הקלטה ועריכה. כבר יש לכם קובץ גולמי? עברו ל" },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט מקצועית" },
    { type: "text", value: ". לחדר בלבד - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "השכרת סטודיו במודיעין" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-studio-modiin": [
    { type: "text", value: "הקלטה שקטה בחדר מבודד עם ליווי טכני. רוצים גם צילום ועריכה? ראו " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ". לפרק שכבר הקלטתם - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכה מלאה" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-editing": [
    { type: "text", value: "שולחים קובץ גולמי ומקבלים פרק מוכן. לקצב חודשי קבוע - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור לעסקים" },
    { type: "text", value: ". להקלטה באולפן - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "סטודיו במודיעין" },
    { type: "text", value: ". לפרויקט שלם - " },
    { type: "link", href: "/podcast/podcast-production", label: "ליווי מא׳ עד ת׳" },
    { type: "text", value: "." },
  ],
  "/podcast/bulk-production": [
    { type: "text", value: "עריכה שוטפת לחברות. פרק מוגמר וקליפים לרשתות. לפרק בודד לפני שמתחייבים: " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: ". להקלטה באולפן: " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: ". להקלטה בחברה: " },
    { type: "link", href: "/business/on-site-studio", label: "אולפן זמני במשרד" },
    { type: "text", value: ". מדריך מלא: " },
    { type: "link", href: "/blog/podcast-production-guide-israel", label: "הפקת פודקאסט בישראל" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-production": [
    { type: "text", value: "בונים פורמט, מיתוג ולוח שידורים. לעריכה שוטפת בלי לנהל כל פרק בנפרד - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". פרק ראשון: " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקה מלאה לפרק בודד" },
    { type: "text", value: " או " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "השכרת אולפן" },
    { type: "text", value: "." },
  ],
  "/podcast/mobile-podcast-at-home": [
    { type: "text", value: "האולפן מגיע אליכם - בית, משרד או אירוע. לפרק באולפן במודיעין ראו " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ". לעריכת פרק בודד " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: ". לקצב חודשי לחברות " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: "." },
  ],
  "/podcast/faq": [
    { type: "text", value: "כאן מרוכזות תשובות על מחירים, הכנה והפצה. להזמנת הפקה מלאה - " },
    { type: "link", href: "/podcast/podcast-recording", label: "צילום והקלטת פודקאסט" },
    { type: "text", value: ". לשכירת חדר בלבד - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: ". לעריכה שוטפת לחברות - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". סקירה כללית - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-with-grandpa": [
    { type: "text", value: "חוויה משפחתית שמשלבת פודקאסט ו" },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר מקצועית" },
    { type: "text", value: ". לפרק רגיל באולפן - " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקה מלאה" },
    { type: "text", value: "." },
  ],
  "/events/dj-events": [
    { type: "text", value: "תקליטן שמבין את הרחבה ואת הקהל. מגיעים ל" },
    { type: "link", href: "/dj-events/cities/shoham", label: "שוהם" },
    { type: "text", value: ", " },
    { type: "link", href: "/dj-events/cities/rehovot", label: "רחובות" },
    { type: "text", value: " ו" },
    { type: "link", href: "/dj-events/cities/jerusalem", label: "ירושלים" },
    { type: "text", value: ". לדיג'ייז שבונים מותג - " },
    { type: "link", href: "/events/dj/voice-tags", label: "תג קולי לסט" },
    { type: "text", value: ". משלימים עם " },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED לתקליטן" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/equipment", label: "הגברה וציוד" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/dj/voice-tags": [
    { type: "text", value: "תג קולי קצר עם אפקטים, מוכן לנגן. לחמישה משפטים לסט שלם ראו " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות לסט" },
    { type: "text", value: ". עוד על קריינות ב" },
    { type: "link", href: "/voiceover/services", label: "שירותי קריינות" },
    { type: "text", value: ", ולתקליטן לאירוע ב" },
    { type: "link", href: "/events/dj-events", label: "DJ לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/stage-led-dj": [
    { type: "text", value: "במה דיגיטלית שמחליפה את שולחן התקליטן הקלאסי. לסאונד מלא - " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לאירועים" },
    { type: "text", value: ". לאפקטים נוספים - " },
    { type: "link", href: "/events/attractions", label: "אטרקציות לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/wedding-attractions-packages": [
    { type: "text", value: "חבילות שמרכזות DJ, אפקטים וציוד. בוחרים " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לחתונה" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לרגע הכניסה" },
    { type: "text", value: " או " },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED" },
    { type: "text", value: " לפי הסגנון שלכם." },
  ],
  "/events/equipment": [
    { type: "text", value: "הגברה מלאה עם טכנאי, או רק ציוד ליום - " },
    { type: "link", href: "/events/equipment/dry-hire", label: "השכרת ציוד" },
    { type: "text", value: ". לזמר חי: " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". שאלות: " },
    { type: "link", href: "/events/equipment/faq", label: "שאלות על הגברה" },
    { type: "text", value: "." },
  ],
  "/events/equipment/dry-hire": [
    { type: "text", value: "ציוד בלבד, בלי טכנאי -מיקסרים, רמקולים וסאב ליום. לחבילה מלאה עם הפעלה: " },
    { type: "link", href: "/events/equipment", label: "הגברה לאירוע" },
    { type: "text", value: ". לזמר עם סאונדמן: " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". תכנון באולם גדול: " },
    { type: "link", href: "/events/equipment/system-tuning", label: "תכנון הגברה" },
    { type: "text", value: "." },
  ],
  "/online/mashup-fixer": [
    { type: "text", value: "מרכז לדיג'יי עמוס: רעיונות מאשאפ בחינם, כלים וייצור כשאין זמן. לסטים ארוכים " },
    { type: "link", href: "/events/dj/pre-built-sets", label: "סטים מוכנים" },
    { type: "text", value: ". לתג קולי: " },
    { type: "link", href: "/events/dj/voice-tags", label: "תג קולי" },
    { type: "text", value: ". לקורס DJ: " },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: "." },
  ],
  "/events/host": [
    { type: "text", value: "מנחה שמוביל את הערב ומתאם מול ספקים. שאלות נפוצות - " },
    { type: "link", href: "/events/host/faq", label: "FAQ מנחה אירועים" },
    { type: "text", value: ". להזמנת אירוע - " },
    { type: "link", href: "/book#events", label: "הזמנה מקוונת" },
    { type: "text", value: "." },
  ],
  "/studio/recording-studio": [
    { type: "text", value: "חדר אקוסטי, מיקרופונים ומפיק בצד. להקלטת שיר לאירוע - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לפודקאסט - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: "." },
  ],
  "/studio/recording-song-modiin": [
    { type: "text", value: "שיר מקורי או קאבר - מוכן להשמעה באירוע. לברכות מוקלטות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: ". לאולפן כללי - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/studio/blessings": [
    { type: "text", value: "ברכות מרגשות באולפן או מהבית. לחתן וכלה - " },
    { type: "link", href: "/studio/blessings/bride-groom-blessing", label: "ברכת חתן וכלה" },
    { type: "text", value: ". לשיר מתנה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: "." },
  ],
  "/studio/blessings/bar-mitzvah": [
    { type: "text", value: "הקלטת דרשות וברכות לבר ובת מצווה. לשיר מקורי לאירוע - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לקליפ וידאו - " },
    { type: "link", href: "/studio/blessings/video-clip", label: "שיר וקליפ" },
    { type: "text", value: ". לכל סוגי הברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/events/attractions": [
    { type: "text", value: "אפקטים לאירועים עם צוות בשטח. לחתונה משלבים " },
    { type: "link", href: "/events/dj-events", label: "תקליטן" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לכניסה" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED" },
    { type: "text", value: "." },
  ],
  "/events/attractions/bubble-machine": [
    { type: "text", value: "בועות סבון שממלאות את הרחבה בצבעים. לווריאציה עם עשן - " },
    { type: "link", href: "/events/attractions/bubble-machine/smoke-bubble-machine-events", label: "מכונת בועות עשן" },
    { type: "text", value: ". לשילוב בחבילה - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות אטרקציות" },
    { type: "text", value: "." },
  ],
  "/events/attractions/bubble-machine/smoke-bubble-machine-events": [
    { type: "text", value: "בועות ועשן יחד לרגע כניסה דרמטי. לבועות קלאסיות - " },
    { type: "link", href: "/events/attractions/bubble-machine", label: "מכונת בועות סבון" },
    { type: "text", value: ". לעשן בחופה - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "מכונת עשן לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/attractions/cold-fireworks": [
    { type: "text", value: "זיקוקים קרים בטוחים לרגע הכניסה. משדרגים עם " },
    { type: "link", href: "/events/attractions/confetti-cannon", label: "תותח קונפטי" },
    { type: "text", value: " או " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לחתונה" },
    { type: "text", value: ". ל-DJ ורחבה - " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/attractions/confetti-cannon": [
    { type: "text", value: "קונפטי מדויק לרגע השיא. לזיקוקים קרים - " },
    { type: "link", href: "/events/attractions/cold-fireworks", label: "זיקוקים קרים" },
    { type: "text", value: ". לרחבה מלאה - " },
    { type: "link", href: "/events/attractions/giant-balloons", label: "בלוני ענק" },
    { type: "text", value: "." },
  ],
  "/events/attractions/giant-balloons": [
    { type: "text", value: "בלוני ענק שמגדילים את האנרגיה ברחבה. משלימים עם " },
    { type: "link", href: "/events/dj-events", label: "תקליטן" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/attractions/confetti-cannon", label: "קונפטי" },
    { type: "text", value: "." },
  ],
  "/events/attractions/wedding-smoking-machine": [
    { type: "text", value: "עשן לרגע הכניסה בלי להעלים את הזוג. לאולמות גדולים - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events", label: "עשן כבד לאירועים" },
    { type: "text", value: ". לזיקוקים - " },
    { type: "link", href: "/events/attractions/cold-fireworks", label: "זיקוקים קרים" },
    { type: "text", value: "." },
  ],
  "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events": [
    { type: "text", value: "עשן כבד לאולמות וחללים גדולים. לחתונות בגן - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לחתונה" },
    { type: "text", value: ". לתותחי עשן - " },
    { type: "link", href: "/events/attractions/smoke-cannons-for-events", label: "תותחי עשן" },
    { type: "text", value: "." },
  ],
  "/events/attractions/smoke-cannons-for-events": [
    { type: "text", value: "תותחי עשן מדויקים לרגעים בוהקים. לעשן בחופה - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "מכונת עשן לחתונה" },
    { type: "text", value: ". לחבילה מלאה - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/equipment/singer-amplification": [
    { type: "text", value: "הגברה נקייה לזמר חי על הבמה. הזמנה - " },
    { type: "link", href: "/book?pkg=basic#singer", label: "הגברה לזמרים באתר" },
    { type: "text", value: ". שאלות - " },
    { type: "link", href: "/events/equipment/faq", label: "שאלות על הגברה" },
    { type: "text", value: "." },
  ],
  "/events/host/faq": [
    { type: "text", value: "תשובות על הנחיית אירועים והזמנה. לשירות המלא - " },
    { type: "link", href: "/events/host", label: "מנחה אירועים" },
    { type: "text", value: ". להזמנה - " },
    { type: "link", href: "/book#events", label: "אטרקציות ו-DJ" },
    { type: "text", value: "." },
  ],
  "/events/equipment/faq": [
    { type: "text", value: "מחירים, צ'ק סאונד והזמנה מקוונת. לזמרים - " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". להזמנה - " },
    { type: "link", href: "/book#singer", label: "טופס הגברה לזמרים" },
    { type: "text", value: "." },
  ],
  "/photo-slideshow": [
    { type: "text", value: "מצגת תמונות מעוצבת לרגעים מרגשים באירוע, כולל " },
    { type: "link", href: "/photo-slideshow#growth-slideshow", label: "מצגת גדילה AI" },
    { type: "text", value: ". לצילום חתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: ". לוידאו - " },
    { type: "link", href: "/video/event-filming", label: "צילום אירועים" },
    { type: "text", value: "." },
  ],
  "/video/presentation": [
    { type: "text", value: "מצגות וידאו מקצועיות לכנסים ואירועים, כולל " },
    { type: "link", href: "/photo-slideshow#growth-slideshow", label: "מצגת גדילה AI" },
    { type: "text", value: ". למצגת תמונות מלאה - " },
    { type: "link", href: "/photo-slideshow", label: "עריכת מצגת לאירוע" },
    { type: "text", value: "." },
  ],
  "/academy": [
    { type: "text", value: "קורסי DJ, הפקה וקריינות באולפן במודיעין. ל" },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: ", ל" },
    { type: "link", href: "/academy/music-production", label: "הפקה מוזיקלית" },
    { type: "text", value: " או ל" },
    { type: "link", href: "/academy/ulpan", label: "שיעור פרטי עברית במודיעין" },
    { type: "text", value: " - בחרו מסלול." },
  ],
  "/academy/home-studio": [
    { type: "text", value: "בונים אולפן ביתי, פודקאסט או חדר משדר? קראו גם את " },
    { type: "link", href: "/blog/studio-guide", label: "המדריך להקמת אולפן" },
    { type: "text", value: ". מעדיפים להקליט אצלנו? " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: " או " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/business/reel-factory": [
    { type: "text", value: "פס ייצור לפרומואים: מעלים חומר גולמי מהאירוע ומקבלים רילס Rave ערוך תוך 24 שעות. לניהול סושיאל לעסקים - " },
    { type: "link", href: "/business/social-media", label: "יקיר איזמירלי" },
    { type: "text", value: ". לשליחת קבצים - " },
    { type: "link", href: "/online/vocal-fix/send-file", label: "העלאה מסודרת" },
    { type: "text", value: "." },
  ],
  "/studio": [
    { type: "text", value: "הקלטות שירים, ברכות ותיקון זיופים באולפן במודיעין. נגיש גם מ" },
    { type: "link", href: "/studio/studio-shoham", label: "שוהם" },
    { type: "text", value: " ו" },
    { type: "link", href: "/studio/studio-rehovot", label: "רחובות" },
    { type: "text", value: ". ליוצרים - " },
    { type: "link", href: "/for-creators", label: "מסלול ליוצרים" },
    { type: "text", value: ". לשיר לחתונה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: ". לשחזור מרחוק - " },
    { type: "link", href: "/online/vocal-fix", label: "תיקון זיופים" },
    { type: "text", value: ". מחירים - " },
    { type: "link", href: "/studio/pricing", label: "מחירון אולפן" },
    { type: "text", value: "." },
  ],
  "/studio/studio-shoham": [
    { type: "text", value: "האולפן במודיעין, כ-10–15 דקות משוהם. לשיר לחופה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/studio/studio-rehovot": [
    { type: "text", value: "האולפן במודיעין, כ-25–30 דקות מרחובות. לשיר לחופה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/dj-events/cities/shoham": [
    { type: "text", value: "DJ לאירועים בשוהם מהבסיס במודיעין. לכל הארץ - " },
    { type: "link", href: "/events/dj-events", label: "מרכז DJ" },
    { type: "text", value: ". לאולפן קרוב - " },
    { type: "link", href: "/studio/studio-shoham", label: "אולפן לשוהם" },
    { type: "text", value: "." },
  ],
  "/dj-events/cities/rehovot": [
    { type: "text", value: "DJ לאירועים ברחובות מהבסיס במודיעין. לכל הארץ - " },
    { type: "link", href: "/events/dj-events", label: "מרכז DJ" },
    { type: "text", value: ". לאולפן קרוב - " },
    { type: "link", href: "/studio/studio-rehovot", label: "אולפן לרחובות" },
    { type: "text", value: "." },
  ],
  "/voiceover": [
    { type: "text", value: "קריינות לסרטונים, מרכזיות ופרסומות. לעסקים - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מסחרית" },
    { type: "text", value: ". לפודקאסט עם קריינות - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: "." },
  ],
  "/online": [
    { type: "text", value: "שלחו קובץ לשחזור, מיקס או תיקון זיופים. לפרטים - " },
    { type: "link", href: "/online/vocal-fix", label: "שיפור קול" },
    { type: "text", value: ", " },
    { type: "link", href: "/online/online-ai-pricing", label: "מחירון AI" },
    { type: "text", value: ". להקלטה באולפן - " },
    { type: "link", href: "/studio", label: "אולפן במודיעין" },
    { type: "text", value: "." },
  ],
  "/pricing": [
    { type: "text", value: "מחירים לפני מע״מ, בלי הפתעות. לחבילות מוכנות - " },
    { type: "link", href: "/packages", label: "חבילות אולפן ואירועים" },
    { type: "text", value: ". להזמנה עם מחיר סופי - " },
    { type: "link", href: "/book", label: "הזמנה מקוונת" },
    { type: "text", value: ". לאולפן - " },
    { type: "link", href: "/studio/pricing", label: "מחירון אולפן" },
    { type: "text", value: ", לפודקאסט - " },
    { type: "link", href: "/podcast", label: "חבילות פודקאסט" },
    { type: "text", value: "." },
  ],
  "/packages": [
    { type: "text", value: "חבילות מוכנות לשיר, פודקאסט וחתונה. למחירון מלא - " },
    { type: "link", href: "/pricing", label: "מחירון" },
    { type: "text", value: ". לזוגות - " },
    { type: "link", href: "/for-couples", label: "מסלול לחתונה" },
    { type: "text", value: ", לפודקאסט - " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט" },
    { type: "text", value: "." },
  ],
  "/book": [
    { type: "text", value: "מחיר לפני מע״מ, וואטסאפ מהיר או הזמנה מפורטת. לחבילות - " },
    { type: "link", href: "/packages", label: "חבילות מוכנות" },
    { type: "text", value: ". לאולפן - " },
    { type: "link", href: "/studio/pricing", label: "מחירון אולפן" },
    { type: "text", value: ", לפודקאסט - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: ", לאירועים - " },
    { type: "link", href: "/events", label: "אטרקציות ו-DJ" },
    { type: "text", value: ". לא בטוחים? " },
    { type: "link", href: "/start", label: "כל השלבים מפנייה ועד קובץ מוכן" },
    { type: "text", value: "." },
  ],
  "/business/content-studio": [
    { type: "text", value: "יום צילום מרוכז באולפן - רילז ערוכים לעסק. לניהול סושיאל - " },
    { type: "link", href: "/business/social-media", label: "ניהול סושיאל" },
    { type: "text", value: ". לספקי אירועים - " },
    { type: "link", href: "/business/reel-factory", label: "מפעל רילס" },
    { type: "text", value: "." },
  ],
  "/studio/recording-song-modiin/gifts": [
    { type: "text", value: "שיר במתנה או רינגטון מצחיק. להקלטה מלאה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לברכה - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/business": [
    { type: "text", value: "תוכן, קריינות ופודקאסט לעסקים. לרילז וסושיאל - " },
    { type: "link", href: "/business/reel-factory", label: "פס ייצור לרילז" },
    { type: "text", value: ", לקריינות - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מקצועית" },
    { type: "text", value: ". לפודקאסט באולפן - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: "." },
  ],
  "/for-couples": [
    { type: "text", value: "כל מה שצריך לחתונה - DJ, אטרקציות, הגברה ואולפן. לתקליטן - " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לחתונה" },
    { type: "text", value: ". לחבילות מוכנות - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: "." },
  ],
  "/for-creators": [
    { type: "text", value: "הקלטה, מיקס ופרסום ליוצרים. לאולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: ". לשיפור הקלטה מרחוק - " },
    { type: "link", href: "/online/vocal-fix", label: "שיפור קול מקוון" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix": [
    { type: "text", value: "שיפור קול, תיקון זיופים והסרת רעשים - הקלטה ביתית לאיכות אולפן. לתיקון זיופים - " },
    { type: "link", href: "/online/vocal-fix/pitch-correction", label: "תיקון זיופים" },
    { type: "text", value: ". למיקס - " },
    { type: "link", href: "/online/vocal-fix/mixing", label: "מיקס ומאסטרינג" },
    { type: "text", value: ". להקלטה באולפן - " },
    { type: "link", href: "/studio", label: "אולפן במודיעין" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix/pitch-correction": [
    { type: "text", value: "תיקון זיופים ידני ומדויק - לא Auto-Tune אוטומטי. למיקס אחרי התיקון - " },
    { type: "link", href: "/online/vocal-fix/mixing", label: "מיקס ומאסטרינג" },
    { type: "text", value: ". להסרת רעשים - " },
    { type: "link", href: "/online/vocal-fix/noise-removal", label: "הסרת רעשים" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix/mixing": [
    { type: "text", value: "מיקס ומאסטרינג מקוון לספוטיפיי ויוטיוב. לתיקון זיופים לפני המיקס - " },
    { type: "link", href: "/online/vocal-fix/pitch-correction", label: "תיקון זיופים" },
    { type: "text", value: ". להקלטה באולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix/noise-removal": [
    { type: "text", value: "הסרת רעשים, אקו וסטטיקה מהקלטות. לתיקון זיופים - " },
    { type: "link", href: "/online/vocal-fix/pitch-correction", label: "תיקון זיופים" },
    { type: "text", value: ". לשיפור קול כללי - " },
    { type: "link", href: "/online/vocal-fix", label: "שיפור קול" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix/eq-fix": [
    { type: "text", value: "כיוון EQ וניקוי תדרים לקול ברור. להסרת רעשים - " },
    { type: "link", href: "/online/vocal-fix/noise-removal", label: "הסרת רעשים" },
    { type: "text", value: ". למיקס מלא - " },
    { type: "link", href: "/online/vocal-fix/mixing", label: "מיקס ומאסטרינג" },
    { type: "text", value: "." },
  ],
  "/online/vocal-fix/volume-balance": [
    { type: "text", value: "איזון עוצמות בין דוברים וקטעים. לניקוי תדרים - " },
    { type: "link", href: "/online/vocal-fix/eq-fix", label: "כיוון EQ" },
    { type: "text", value: ". למיקס מלא - " },
    { type: "link", href: "/online/vocal-fix/mixing", label: "מיקס ומאסטרינג" },
    { type: "text", value: "." },
  ],
  "/video": [
    { type: "text", value: "צילום ועריכת וידאו לאירועים ועסקים. לצילום אירוע - " },
    { type: "link", href: "/video/event-filming", label: "צילום אירועים" },
    { type: "text", value: ". לפרויקט תאגידי - " },
    { type: "link", href: "/video/corporate-video", label: "וידאו לעסקים" },
    { type: "text", value: ". לצילום חתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: "." },
  ],
  "/video/event-filming": [
    { type: "text", value: "צילום וידאו מקצועי לאירועים ואירועים מיוחדים. לצילום חתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: ". לוידאו תאגידי - " },
    { type: "link", href: "/video/corporate-video", label: "וידאו לעסקים" },
    { type: "text", value: "." },
  ],
  "/video/corporate-video": [
    { type: "text", value: "וידאו תדמיתי לעסקים - קצר, ממוקד ומקצועי. לרילז לסושיאל - " },
    { type: "link", href: "/business/reel-factory", label: "פס ייצור לרילז" },
    { type: "text", value: ". לקריינות לסרטון - " },
    { type: "link", href: "/voiceover/services", label: "שירותי קריינות" },
    { type: "text", value: "." },
  ],
  "/photography": [
    { type: "text", value: "צלם מקצועי לאירועים ורגעים מיוחדים. לחתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: ". לאירועים - " },
    { type: "link", href: "/photography/events", label: "צילום אירועים" },
    { type: "text", value: ". לוידאו - " },
    { type: "link", href: "/video", label: "הפקת וידאו" },
    { type: "text", value: "." },
  ],
  "/photography/wedding": [
    { type: "text", value: "צלם חתונות עם ניסיון רב באירועים. לוידאו - " },
    { type: "link", href: "/video/event-filming", label: "צילום אירועים בוידאו" },
    { type: "text", value: ". לתקליטן - " },
    { type: "link", href: "/events/dj-events", label: "DJ לחתונה" },
    { type: "text", value: "." },
  ],
  "/photography/events": [
    { type: "text", value: "צילום אירועים מקצועי - בר מצווה, ימי הולדת ועוד. לצילום חתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: ". לוידאו לאירוע - " },
    { type: "link", href: "/video/event-filming", label: "צילום אירועים בוידאו" },
    { type: "text", value: "." },
  ],
  "/voiceover/services": [
    { type: "text", value: "קריינות לסרטונים, מרכזיות ופרסומות. לקריינות לעסקים - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מסחרית" },
    { type: "text", value: ". לקורס קריינות - " },
    { type: "link", href: "/voiceover/course", label: "קורס קריינות" },
    { type: "text", value: "." },
  ],
  "/voiceover/course": [
    { type: "text", value: "קורס קריינות מקצועי - טכניקה, יציאה לשוק ועבודה מהאולפן. לשירותי קריינות - " },
    { type: "link", href: "/voiceover/services", label: "שירותי קריינות" },
    { type: "text", value: ". לאולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/academy/dj-course": [
    { type: "text", value: "קורס DJ מקיף - בסיס, מיקס וביצוע חי. לשלב הבא - " },
    { type: "link", href: "/academy/music-production", label: "הפקה מוזיקלית" },
    { type: "text", value: ". לאולפן להקלטת מיקסים - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/academy/music-production": [
    { type: "text", value: "הפקה מוזיקלית - בונים טראק מאפס עד מאסטר. לקורס DJ לצד ההפקה - " },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: ". להקלטה באולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/academy/ulpan": [
    { type: "text", value: "שיעורי עברית פרטיים בגישה תקשורתית. לשיעורים פרטיים נוספים - " },
    { type: "link", href: "/academy/private-lessons", label: "שיעורים פרטיים" },
    { type: "text", value: ". לכל הקורסים - " },
    { type: "link", href: "/academy", label: "האקדמיה" },
    { type: "text", value: "." },
  ],
  "/academy/hebrew-lessons": [
    { type: "text", value: "לימוד עברית פרטי ומותאם אישית. לאולפן עברית - " },
    { type: "link", href: "/academy/ulpan", label: "אולפן עברית" },
    { type: "text", value: ". לשיעורים פרטיים בכל תחום - " },
    { type: "link", href: "/academy/private-lessons", label: "שיעורים פרטיים" },
    { type: "text", value: "." },
  ],
  "/academy/private-lessons": [
    { type: "text", value: "שיעורים פרטיים בהפקה, DJ, קריינות ועברית. לתחום ספציפי - " },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: " או " },
    { type: "link", href: "/academy/music-production", label: "הפקה מוזיקלית" },
    { type: "text", value: "." },
  ],
  "/studio/pricing": [
    { type: "text", value: "מחירון אולפן לפני מע\"מ - חצי שעה, שעה וחבילות. לחבילות מוכנות - " },
    { type: "link", href: "/packages", label: "חבילות אולפן" },
    { type: "text", value: ". להזמנה - " },
    { type: "link", href: "/book", label: "הזמנה מקוונת" },
    { type: "text", value: ". למחירון כללי - " },
    { type: "link", href: "/pricing", label: "מחירון מרכזי" },
    { type: "text", value: "." },
  ],
  "/studio/mobile-studio": [
    { type: "text", value: "האולפן מגיע אליכם - בית, אולם או חברה. לאולפן פיזי במודיעין - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: ". לפודקאסט נייד - " },
    { type: "link", href: "/podcast/mobile-podcast-at-home", label: "פודקאסט נייד" },
    { type: "text", value: "." },
  ],
  "/studio/studio-jerusalem": [
    { type: "text", value: "האולפן במודיעין, נגיש מירושלים. לשיר לחופה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/studio/blessings/bride-groom-blessing": [
    { type: "text", value: "ברכה מרגשת לחתן וכלה מהמשפחה, מוקלטת באולפן. לשיר מתנה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: ". לכל סוגי הברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/studio/blessings/bat-mitzvah-clip": [
    { type: "text", value: "קליפ מיוחד לבת מצווה עם שיר וברכות. לבר מצווה - " },
    { type: "link", href: "/studio/blessings/bar-mitzvah", label: "הקלטה לבר מצווה" },
    { type: "text", value: ". לשיר מקורי - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: "." },
  ],
  "/studio/blessings/video-clip": [
    { type: "text", value: "שיר וקליפ מרגש לאירועים מיוחדים. לברכות בלבד - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: ". לשיר לחתונה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: "." },
  ],
  "/dj-events/cities/jerusalem": [
    { type: "text", value: "DJ לאירועים בירושלים מהבסיס במודיעין. לכל הארץ - " },
    { type: "link", href: "/events/dj-events", label: "מרכז DJ" },
    { type: "text", value: ". לאטרקציות בירושלים - " },
    { type: "link", href: "/events/attractions/jerusalem", label: "אטרקציות לאירועים בירושלים" },
    { type: "text", value: "." },
  ],
  "/events/dj/pre-built-sets": [
    { type: "text", value: "סטים מוכנים לדיג'יייז - שעה של מוזיקה ערוכה לנגן. לתג קולי לסט - " },
    { type: "link", href: "/events/dj/voice-tags", label: "תג קולי" },
    { type: "text", value: ". לתקליטן לאירוע - " },
    { type: "link", href: "/events/dj-events", label: "DJ לאירועים" },
    { type: "text", value: "." },
  ],
  "/podcast/corporate-podcast": [
    { type: "text", value: "פודקאסט לחברות - תוכן מקצועי שמייצר סמכות ולידים. לפס ייצור חודשי - " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". לפרק ראשון - " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט" },
    { type: "text", value: "." },
  ],
  "/podcast/self-service-studio": [
    { type: "text", value: "חדר מבודד עם ציוד מוכן - מגיעים ומקליטים לבד. לליווי טכני מלא - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן פודקאסט" },
    { type: "text", value: ". לעריכה אחרי ההקלטה - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: "." },
  ],
  "/podcast/jerusalem": [
    { type: "text", value: "הקלטת פודקאסט באולפן המודיעין, נגיש מירושלים. לעריכה - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: ". לפרק שלם - " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקה מלאה" },
    { type: "text", value: "." },
  ],
  "/stuttering": [
    { type: "text", value: "ליווי לגמגום בגישת NeverMind - ילדים, נוער ומבוגרים. לקורס המלא - " },
    { type: "link", href: "/academy/stuttering-course", label: "קורס גמגום" },
    { type: "text", value: ". לפגישה ראשונה - " },
    { type: "link", href: "/clinic", label: "קליניקה" },
    { type: "text", value: "." },
  ],
  "/clinic": [
    { type: "text", value: "פגישת אבחון וגיבוש מסלול אישי לגמגום. לתוכנית מלאה - " },
    { type: "link", href: "/academy/stuttering-course", label: "קורס גמגום" },
    { type: "text", value: ". למידע כללי - " },
    { type: "link", href: "/stuttering", label: "ליווי לגמגום" },
    { type: "text", value: "." },
  ],
  "/events/attractions/jerusalem": [
    { type: "text", value: "עשן כבד, זיקוקים קרים ובועות לאירועים בירושלים ממודיעין. לתקליטן - " },
    { type: "link", href: "/dj-events/cities/jerusalem", label: "DJ בירושלים" },
    { type: "text", value: ". לחבילות - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות אירוע" },
    { type: "text", value: "." },
  ],
  "/business/audiobooks": [
    { type: "text", value: "הקלטה, עריכה ומאסטרינג לספר קולי. לקריינות מסחרית - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מקצועית" },
    { type: "text", value: ". לקורס קריינות - " },
    { type: "link", href: "/academy/voiceover", label: "קורס קריינות" },
    { type: "text", value: "." },
  ],
  "/business/audio-branding": [
    { type: "text", value: "מיתוג קולי לעסק - לוגו, המתנה ומסרים. לקריינות - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מסחרית" },
    { type: "text", value: ". למרכז עסקים - " },
    { type: "link", href: "/business", label: "שירותים לעסקים" },
    { type: "text", value: "." },
  ],
  "/business/on-site-studio": [
    { type: "text", value: "אולפן זמני במשרד או באתר הלקוח. לתוכן שוטף - " },
    { type: "link", href: "/business/content-studio", label: "אולפן תוכן" },
    { type: "text", value: ". לפודקאסט חברות - " },
    { type: "link", href: "/podcast/corporate-podcast", label: "פודקאסט לחברות" },
    { type: "text", value: "." },
  ],
  "/business/employer-branding": [
    { type: "text", value: "תוכן מעסיק מוביל לגיוס והשארה. לפודקאסט פנים-ארגוני - " },
    { type: "link", href: "/podcast/corporate-podcast", label: "פודקאסט לחברות" },
    { type: "text", value: ". לרילז - " },
    { type: "link", href: "/business/reel-factory", label: "מפעל רילס" },
    { type: "text", value: "." },
  ],
  "/business/corporate-songs": [
    { type: "text", value: "שיר מקורי לחברה - ג'ינגל, המנון או שיר אירוע. להקלטה באולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: ". לברכות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: "." },
  ],
  "/online/voice-cloning": [
    { type: "text", value: "שיבוט קול מבוקר לפרויקטים מסחריים. לקריינות חיה - " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות מקצועית" },
    { type: "text", value: ". לשירותי AI נוספים - " },
    { type: "link", href: "/online", label: "שירותים אונליין" },
    { type: "text", value: "." },
  ],
  "/online/legacy-digitization": [
    { type: "text", value: "המרת קלטות, ויניל וקלטות וידאו לדיגיטל. לתמלול - " },
    { type: "link", href: "/online/transcription", label: "תמלול וכתוביות" },
    { type: "text", value: ". לשחזור אודיו - " },
    { type: "link", href: "/online/vocal-fix", label: "תיקון הקלטות" },
    { type: "text", value: "." },
  ],
  "/online/transcription": [
    { type: "text", value: "תמלול, כתוביות ותרגום לסרטונים ופודקאסטים. לעריכת פודקאסט - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: ". לדיגיטציה - " },
    { type: "link", href: "/online/legacy-digitization", label: "דיגיטציה של ארכיון" },
    { type: "text", value: "." },
  ],
  "/academy/workshops": [
    { type: "text", value: "סדנאות מוזיקה, DJ ותוכן לארגונים וקבוצות. לקורס DJ - " },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: ". לשיעורים פרטיים - " },
    { type: "link", href: "/academy/private-lessons", label: "שיעורים פרטיים" },
    { type: "text", value: "." },
  ],
  "/equipment/used-gear": [
    { type: "text", value: "ציוד אולפן, הגברה ותאורה יד שנייה מהפקות שלנו. לאולפן - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: ". להשכרת הגברה - " },
    { type: "link", href: "/events/equipment", label: "ציוד לאירועים" },
    { type: "text", value: "." },
  ],
  "/about": [
    { type: "text", value: "אולפן, DJ ואטרקציות במודיעין, 20+ שנות ניסיון. לפודקאסט - " },
    { type: "link", href: "/podcast", label: "מרכז פודקאסט" },
    { type: "text", value: ". לחתונה - " },
    { type: "link", href: "/events/dj-events", label: "DJ לחתונה" },
    { type: "text", value: "." },
  ],
  "/about/faq": [
    { type: "text", value: "להקלטת שיר באולפן - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". ל-DJ בחתונה - " },
    { type: "link", href: "/events/dj-events", label: "DJ לחתונה" },
    { type: "text", value: ". להזמנה מקוונת - " },
    { type: "link", href: "/book", label: "הזמנה מקוונת" },
    { type: "text", value: "." },
  ],
  "/voucher": [
    { type: "text", value: "שובר מתנה לאולפן הקלטות, אטרקציות לאירוע או הפקה מלאה. מתאים ל" },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר באולפן" },
    { type: "text", value: ", " },
    { type: "link", href: "/studio/blessings", label: "ברכות מוקלטות" },
    { type: "text", value: " או " },
    { type: "link", href: "/events/attractions", label: "אטרקציות לאירוע" },
    { type: "text", value: "." },
  ],
};

export function getIntroSegments(pathname: string): IntroSegment[] | undefined {
  const normalized = pathname.replace(/\/$/, "") || "/";
  return PAGE_INTRO_SEGMENTS[normalized];
}
