/**
 * Contextual internal links (max 2-3 per page) - edit here when adding routes.
 * Rendered by ContextualIntroParagraph; anchor text stays natural Hebrew.
 */

export type IntroSegment =
  | { type: "text"; value: string }
  | { type: "link"; href: string; label: string };

export const PAGE_INTRO_SEGMENTS: Partial<Record<string, IntroSegment[]>> = {
  "/events": [
    { type: "text", value: "הפקה מלאה לאירוע - DJ, הגברה, הנחיית קהל וניהול לו\"ז. לחתונה עם אטרקציות חובה ראו " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: ", למנחה מקצועי - " },
    { type: "link", href: "/events/host", label: "הנחיית אירועים" },
    { type: "text", value: "." },
  ],
  "/podcast": [
    { type: "text", value: "מגיעים לאולפן, מקליטים, ויוצאים עם פרק מוכן. לעריכה שוטפת לחברות — " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". לפרק בודד: " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ", לשכירת חדר — " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-recording": [
    { type: "text", value: "הפתרון המלא כולל צילום, הקלטה ועריכה. כבר יש לכם קובץ גולמי? עברו ל" },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט מקצועית" },
    { type: "text", value: ". לחדר בלבד - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "השכרת סטודיו במודיעין" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-studio-modiin": [
    { type: "text", value: "הקלטה שקטה בחדר מבודד עם ליווי טכני. רוצים גם צילום ועריכה? ראו " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ". לפרק שכבר הקלטתם - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכה מלאה" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-editing": [
    { type: "text", value: "שולחים קובץ גולמי ומקבלים פרק מוכן. לקצב חודשי קבוע — " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור לעסקים" },
    { type: "text", value: ". להקלטה באולפן — " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "סטודיו במודיעין" },
    { type: "text", value: ". לפרויקט שלם — " },
    { type: "link", href: "/podcast/podcast-production", label: "ליווי מא׳ עד ת׳" },
    { type: "text", value: "." },
  ],
  "/podcast/bulk-production": [
    { type: "text", value: "עריכה שוטפת לחברות. פרק מוגמר וקליפים לרשתות. לפרק בודד לפני שמתחייבים: " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: ". להקלטה באולפן: " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: ". להקלטה בחברה: " },
    { type: "link", href: "/business/on-site-studio", label: "אולפן זמני במשרד" },
    { type: "text", value: ". מדריך מלא: " },
    { type: "link", href: "/blog/podcast-production-guide-israel", label: "הפקת פודקאסט בישראל" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-production": [
    { type: "text", value: "בונים פורמט, מיתוג ולוח שידורים. לעריכה שוטפת בלי לנהל כל פרק בנפרד — " },
    { type: "link", href: "/podcast/bulk-production", label: "פס ייצור" },
    { type: "text", value: ". פרק ראשון: " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקה מלאה לפרק בודד" },
    { type: "text", value: " או " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "השכרת אולפן" },
    { type: "text", value: "." },
  ],
  "/podcast/mobile-podcast-at-home": [
    { type: "text", value: "האולפן מגיע אליכם - בית, משרד או אירוע. לפרק באולפן במודיעין ראו " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקת פודקאסט מלאה" },
    { type: "text", value: ". לעריכה בלבד - " },
    { type: "link", href: "/podcast/podcast-editing", label: "עריכת פודקאסט" },
    { type: "text", value: "." },
  ],
  "/podcast/faq": [
    { type: "text", value: "כאן מרוכזות תשובות על מחירים, הכנה והפצה. להזמנת הפקה מלאה - " },
    { type: "link", href: "/podcast/podcast-recording", label: "צילום והקלטת פודקאסט" },
    { type: "text", value: ". לשכירת חדר בלבד - " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: ". סקירה כללית - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: "." },
  ],
  "/podcast/podcast-with-grandpa": [
    { type: "text", value: "חוויה משפחתית שמשלבת פודקאסט ו" },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר מקצועית" },
    { type: "text", value: ". לפרק רגיל באולפן - " },
    { type: "link", href: "/podcast/podcast-recording", label: "הפקה מלאה" },
    { type: "text", value: "." },
  ],
  "/events/dj-events": [
    { type: "text", value: "תקליטן שמבין את הרחבה ואת הקהל. לדיג'ייז שבונים מותג — " },
    { type: "link", href: "/events/dj/voice-tags", label: "תג קולי לסט" },
    { type: "text", value: ". משלימים עם " },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED לתקליטן" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/equipment", label: "הגברה וציוד" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/dj/voice-tags": [
    { type: "text", value: "תג קולי קצר עם אפקטים, מוכן לנגן. לחמישה משפטים לסט שלם ראו " },
    { type: "link", href: "/business/professional-voiceover", label: "קריינות לסט" },
    { type: "text", value: ". עוד על קריינות ב" },
    { type: "link", href: "/voiceover/services", label: "שירותי קריינות" },
    { type: "text", value: ", ולתקליטן לאירוע ב" },
    { type: "link", href: "/events/dj-events", label: "DJ לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/stage-led-dj": [
    { type: "text", value: "במה דיגיטלית שמחליפה את שולחן התקליטן הקלאסי. לסאונד מלא - " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לאירועים" },
    { type: "text", value: ". לאפקטים נוספים - " },
    { type: "link", href: "/events/attractions", label: "אטרקציות לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/wedding-attractions-packages": [
    { type: "text", value: "חבילות שמרכזות DJ, אפקטים וציוד. בוחרים " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לחתונה" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לרגע הכניסה" },
    { type: "text", value: " או " },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED" },
    { type: "text", value: " לפי הסגנון שלכם." },
  ],
  "/events/equipment": [
    { type: "text", value: "הגברה מלאה עם טכנאי, או רק ציוד ליום — " },
    { type: "link", href: "/events/equipment/dry-hire", label: "השכרת ציוד" },
    { type: "text", value: ". לזמר חי: " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". שאלות: " },
    { type: "link", href: "/events/equipment/faq", label: "שאלות על הגברה" },
    { type: "text", value: "." },
  ],
  "/events/equipment/dry-hire": [
    { type: "text", value: "ציוד בלבד, בלי טכנאי — מיקסרים, רמקולים וסאב ליום. לחבילה מלאה עם הפעלה: " },
    { type: "link", href: "/events/equipment", label: "הגברה לאירוע" },
    { type: "text", value: ". לזמר עם סאונדמן: " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". תכנון באולם גדול: " },
    { type: "link", href: "/events/equipment/system-tuning", label: "תכנון הגברה" },
    { type: "text", value: "." },
  ],
  "/online/mashup-fixer": [
    { type: "text", value: "מרכז לדיג'יי עמוס: רעיונות מאשאפ בחינם, כלים (Fadr, Gemini) וייצור כשאין זמן. לסטים ארוכים — " },
    { type: "link", href: "/events/dj/pre-built-sets", label: "סטים מוכנים" },
    { type: "text", value: ". לתג קולי: " },
    { type: "link", href: "/events/dj/voice-tags", label: "תג קולי" },
    { type: "text", value: "." },
  ],
  "/events/host": [
    { type: "text", value: "מנחה שמוביל את הערב ומתאם מול ספקים. שאלות נפוצות - " },
    { type: "link", href: "/events/host/faq", label: "FAQ מנחה אירועים" },
    { type: "text", value: ". להזמנת אירוע - " },
    { type: "link", href: "/book#events", label: "הזמנה מקוונת" },
    { type: "text", value: "." },
  ],
  "/studio/recording-studio": [
    { type: "text", value: "חדר אקוסטי, מיקרופונים ומפיק בצד. להקלטת שיר לאירוע - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר במודיעין" },
    { type: "text", value: ". לפודקאסט - " },
    { type: "link", href: "/podcast", label: "מרכז הפודקאסט" },
    { type: "text", value: "." },
  ],
  "/studio/recording-song-modiin": [
    { type: "text", value: "שיר מקורי או קאבר - מוכן להשמעה באירוע. לברכות מוקלטות - " },
    { type: "link", href: "/studio/blessings", label: "הקלטת ברכות" },
    { type: "text", value: ". לאולפן כללי - " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/studio/blessings": [
    { type: "text", value: "ברכות מרגשות באולפן או מהבית. לחתן וכלה - " },
    { type: "link", href: "/studio/blessings/bride-groom-blessing", label: "ברכת חתן וכלה" },
    { type: "text", value: ". לשיר מתנה - " },
    { type: "link", href: "/studio/recording-song-modiin", label: "הקלטת שיר" },
    { type: "text", value: "." },
  ],
  "/events/attractions": [
    { type: "text", value: "אפקטים לאירועים עם צוות בשטח. לחתונה משלבים " },
    { type: "link", href: "/events/dj-events", label: "תקליטן" },
    { type: "text", value: ", " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לכניסה" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/stage-led-dj", label: "עמדת LED" },
    { type: "text", value: "." },
  ],
  "/events/attractions/bubble-machine": [
    { type: "text", value: "בועות סבון שממלאות את הרחבה בצבעים. לווריאציה עם עשן - " },
    { type: "link", href: "/events/attractions/bubble-machine/smoke-bubble-machine-events", label: "מכונת בועות עשן" },
    { type: "text", value: ". לשילוב בחבילה - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות אטרקציות" },
    { type: "text", value: "." },
  ],
  "/events/attractions/bubble-machine/smoke-bubble-machine-events": [
    { type: "text", value: "בועות ועשן יחד לרגע כניסה דרמטי. לבועות קלאסיות - " },
    { type: "link", href: "/events/attractions/bubble-machine", label: "מכונת בועות סבון" },
    { type: "text", value: ". לעשן בחופה - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "מכונת עשן לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/attractions/cold-fireworks": [
    { type: "text", value: "זיקוקים קרים בטוחים לרגע הכניסה. משדרגים עם " },
    { type: "link", href: "/events/attractions/confetti-cannon", label: "תותח קונפטי" },
    { type: "text", value: " או " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לחתונה" },
    { type: "text", value: ". ל-DJ ורחבה - " },
    { type: "link", href: "/events/dj-events", label: "תקליטן לאירועים" },
    { type: "text", value: "." },
  ],
  "/events/attractions/confetti-cannon": [
    { type: "text", value: "קונפטי מדויק לרגע השיא. לזיקוקים קרים - " },
    { type: "link", href: "/events/attractions/cold-fireworks", label: "זיקוקים קרים" },
    { type: "text", value: ". לרחבה מלאה - " },
    { type: "link", href: "/events/attractions/giant-balloons", label: "בלוני ענק" },
    { type: "text", value: "." },
  ],
  "/events/attractions/giant-balloons": [
    { type: "text", value: "בלוני ענק שמגדילים את האנרגיה ברחבה. משלימים עם " },
    { type: "link", href: "/events/dj-events", label: "תקליטן" },
    { type: "text", value: " ו" },
    { type: "link", href: "/events/attractions/confetti-cannon", label: "קונפטי" },
    { type: "text", value: "." },
  ],
  "/events/attractions/wedding-smoking-machine": [
    { type: "text", value: "עשן לרגע הכניסה בלי להעלים את הזוג. לאולמות גדולים - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events", label: "עשן כבד לאירועים" },
    { type: "text", value: ". לזיקוקים - " },
    { type: "link", href: "/events/attractions/cold-fireworks", label: "זיקוקים קרים" },
    { type: "text", value: "." },
  ],
  "/events/attractions/wedding-smoking-machine/heavy-smoke-large-events": [
    { type: "text", value: "עשן כבד לאולמות וחללים גדולים. לחתונות בגן - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "עשן לחתונה" },
    { type: "text", value: ". לתותחי עשן - " },
    { type: "link", href: "/events/attractions/smoke-cannons-for-events", label: "תותחי עשן" },
    { type: "text", value: "." },
  ],
  "/events/attractions/smoke-cannons-for-events": [
    { type: "text", value: "תותחי עשן מדויקים לרגעים בוהקים. לעשן בחופה - " },
    { type: "link", href: "/events/attractions/wedding-smoking-machine", label: "מכונת עשן לחתונה" },
    { type: "text", value: ". לחבילה מלאה - " },
    { type: "link", href: "/events/wedding-attractions-packages", label: "חבילות לחתונה" },
    { type: "text", value: "." },
  ],
  "/events/equipment/singer-amplification": [
    { type: "text", value: "הגברה נקייה לזמר חי על הבמה. הזמנה - " },
    { type: "link", href: "/book?pkg=basic#singer", label: "הגברה לזמרים באתר" },
    { type: "text", value: ". שאלות - " },
    { type: "link", href: "/events/equipment/faq", label: "שאלות על הגברה" },
    { type: "text", value: "." },
  ],
  "/events/host/faq": [
    { type: "text", value: "תשובות על הנחיית אירועים והזמנה. לשירות המלא - " },
    { type: "link", href: "/events/host", label: "מנחה אירועים" },
    { type: "text", value: ". להזמנה - " },
    { type: "link", href: "/book#events", label: "אטרקציות ו-DJ" },
    { type: "text", value: "." },
  ],
  "/events/equipment/faq": [
    { type: "text", value: "מחירים, צ'ק סאונד והזמנה מקוונת. לזמרים - " },
    { type: "link", href: "/events/equipment/singer-amplification", label: "הגברה לזמרים" },
    { type: "text", value: ". להזמנה - " },
    { type: "link", href: "/book#singer", label: "טופס הגברה לזמרים" },
    { type: "text", value: "." },
  ],
  "/photo-slideshow": [
    { type: "text", value: "מצגת תמונות מעוצבת לרגעים מרגשים באירוע, כולל " },
    { type: "link", href: "/photo-slideshow#growth-slideshow", label: "מצגת גדילה AI" },
    { type: "text", value: ". לצילום חתונה - " },
    { type: "link", href: "/photography/wedding", label: "צילום חתונות" },
    { type: "text", value: ". לוידאו - " },
    { type: "link", href: "/video/event-filming", label: "צילום אירועים" },
    { type: "text", value: "." },
  ],
  "/video/presentation": [
    { type: "text", value: "מצגות וידאו מקצועיות לכנסים ואירועים, כולל " },
    { type: "link", href: "/photo-slideshow#growth-slideshow", label: "מצגת גדילה AI" },
    { type: "text", value: ". למצגת תמונות מלאה - " },
    { type: "link", href: "/photo-slideshow", label: "עריכת מצגת לאירוע" },
    { type: "text", value: "." },
  ],
  "/academy": [
    { type: "text", value: "קורסי DJ, הפקה וקריינות באולפן במודיעין. ל" },
    { type: "link", href: "/academy/dj-course", label: "קורס DJ" },
    { type: "text", value: ", ל" },
    { type: "link", href: "/academy/music-production", label: "הפקה מוזיקלית" },
    { type: "text", value: " או ל" },
    { type: "link", href: "/academy/ulpan", label: "שיעור פרטי עברית במודיעין" },
    { type: "text", value: " - בחרו מסלול." },
  ],
  "/academy/home-studio": [
    { type: "text", value: "בונים אולפן ביתי, פודקאסט או חדר משדר? קראו גם את " },
    { type: "link", href: "/blog/studio-guide", label: "המדריך להקמת אולפן" },
    { type: "text", value: ". מעדיפים להקליט אצלנו? " },
    { type: "link", href: "/podcast/podcast-studio-modiin", label: "אולפן במודיעין" },
    { type: "text", value: " או " },
    { type: "link", href: "/studio/recording-studio", label: "אולפן הקלטות" },
    { type: "text", value: "." },
  ],
  "/business/reel-factory": [
    { type: "text", value: "פס ייצור לפרומואים: מעלים חומר גולמי מהאירוע ומקבלים רילס Rave ערוך תוך 24 שעות. לניהול סושיאל לעסקים - " },
    { type: "link", href: "/business/social-media", label: "יקיר איזמירלי" },
    { type: "text", value: ". לשליחת קבצים - " },
    { type: "link", href: "/online/vocal-fix/send-file", label: "העלאה מסודרת" },
    { type: "text", value: "." },
  ],
};

export function getIntroSegments(pathname: string): IntroSegment[] | undefined {
  const normalized = pathname.replace(/\/$/, "") || "/";
  return PAGE_INTRO_SEGMENTS[normalized];
}
