/**
 * מפיק היטלים קלים של מאגרי התוכן, לשימוש ברכיבי לקוח.
 *
 * הרקע: components/layout/Breadcrumbs.tsx הוא רכיב לקוח, והוא ייבא את
 * lib/breadcrumbs/build-trail.ts שייבא את lib/data/blog.ts (409KB) ואת
 * lib/data/services.ts (173KB). זו הייתה נקודת הכניסה **היחידה** של blog.ts
 * ללקוח בכל הריפו, והיא שלחה כ-585KB לכל דפדפן בכל עמוד, גם בעמוד הבית
 * שבו buildBreadcrumbTrail מחזיר [] לפני שהוא נוגע בנתונים.
 *
 * המפה כאן מכילה רק מה שפירורי הלחם באמת צריכים: slug לכותרת.
 *
 * מפיק שני קבצים:
 *   lib/data/breadcrumb-titles.generated.ts   slug לכותרת (בלוג ושירותים)
 *   lib/data/glossary-tooltips.generated.ts   ביטוי ל-slug, ו-slug להגדרה
 *
 * Run: npm run generate:client-data      - כותב את הקבצים
 * Run: npm run audit:client-data         - מוודא בלבד, נכשל אם התיישנו
 *
 * הנתונים מיובאים ולא נגזרים ב-regex, כי כותרות בעברית מכילות מרכאות
 * וגרשיים. סקריפט slug אחר בריפו כן משתמש ב-regex, וזה בטוח שם כי slug
 * הוא ASCII.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { BLOG_POSTS } from "../lib/data/blog";
import { GLOSSARY_PHRASE_TO_SLUG, GLOSSARY_TERMS } from "../lib/data/glossary";
import {
  EVENTS_SERVICES,
  PHOTOGRAPHY_SERVICES,
  STUDIO_SERVICES,
  VIDEO_SERVICES,
  VOICEOVER_SERVICES,
  type ServiceEntity,
} from "../lib/data/services";

const root = resolve(import.meta.dirname, "..");
const crumbsPath = resolve(root, "lib/data/breadcrumb-titles.generated.ts");
const glossaryPath = resolve(root, "lib/data/glossary-tooltips.generated.ts");

const blogTitles: Record<string, string> = {};
for (const post of BLOG_POSTS) blogTitles[post.slug] = post.title;

const serviceTitles: Record<string, string> = {};
const registries = [
  STUDIO_SERVICES,
  VOICEOVER_SERVICES,
  EVENTS_SERVICES,
  VIDEO_SERVICES,
  PHOTOGRAPHY_SERVICES,
];
for (const registry of registries) {
  for (const service of Object.values(registry) as ServiceEntity[]) {
    serviceTitles[service.slug] = service.title;
  }
}

if (Object.keys(blogTitles).length === 0 || Object.keys(serviceTitles).length === 0) {
  console.error("generate:breadcrumb-titles — מאגר ריק. משהו נשבר בייבוא.");
  process.exit(1);
}

const definitions: Record<string, string> = {};
const labels: Record<string, string> = {};
for (const term of GLOSSARY_TERMS) {
  definitions[term.slug] = term.definition;
  labels[term.slug] = term.termHe;
}

const glossaryBody = `/** AUTO-GENERATED by scripts/generate-client-data.ts - do not edit */

/**
 * הפרויקציה שרכיבי הלקוח באמת צריכים מהמונחון: ביטוי לזיהוי, ו-slug להגדרה.
 * lib/data/glossary.ts מלא הוא 62KB עם קטגוריות, מונחים קשורים ושירותים
 * קשורים, ואף אחד מהם לא נדרש כדי לצייר טולטיפ.
 */
export const GLOSSARY_PHRASE_SLUGS: Readonly<Record<string, string>> = ${JSON.stringify(GLOSSARY_PHRASE_TO_SLUG, null, 2)};

export const GLOSSARY_DEFINITIONS: Readonly<Record<string, string>> = ${JSON.stringify(definitions, null, 2)};

/** slug לשם המונח בעברית */
export const GLOSSARY_TERM_LABELS: Readonly<Record<string, string>> = ${JSON.stringify(labels, null, 2)};

/** הביטויים ממוינים מהארוך לקצר, כדי שהתאמת הרג׳קס תעדיף את הספציפי */
export const GLOSSARY_TOOLTIP_PHRASE_LIST: readonly { phrase: string; slug: string }[] =
  Object.entries(GLOSSARY_PHRASE_SLUGS)
    .map(([phrase, slug]) => ({ phrase, slug }))
    .sort((a, b) => b.phrase.length - a.phrase.length);
`;

const body = `/** AUTO-GENERATED by scripts/generate-breadcrumb-titles.ts - do not edit */

/** slug של פוסט בלוג לכותרת שלו */
export const BREADCRUMB_BLOG_TITLES: Readonly<Record<string, string>> = ${JSON.stringify(blogTitles, null, 2)};

/** slug של עמוד שירות (בלי לוכסן מוביל) לכותרת שלו */
export const BREADCRUMB_SERVICE_TITLES: Readonly<Record<string, string>> = ${JSON.stringify(serviceTitles, null, 2)};
`;

const hash = createHash("sha256").update(body).digest("hex").slice(0, 12);

function matches(file: string, expected: string): boolean {
  try {
    return readFileSync(file, "utf8").replace(/\r\n/g, "\n") === expected;
  } catch {
    return false;
  }
}

if (process.argv.includes("--check")) {
  const stale = [
    matches(crumbsPath, body) ? null : "lib/data/breadcrumb-titles.generated.ts",
    matches(glossaryPath, glossaryBody) ? null : "lib/data/glossary-tooltips.generated.ts",
  ].filter(Boolean) as string[];
  if (stale.length === 0) {
    console.log(
      `audit:client-data OK — ${Object.keys(blogTitles).length} פוסטים, ${Object.keys(serviceTitles).length} שירותים, ${GLOSSARY_TERMS.length} מונחים. תואם למקור.`,
    );
    process.exit(0);
  }
  console.error("=== audit:client-data ===\n");
  for (const f of stale) console.error(`  ✗ ${f} לא קיים או התיישן מול המקור.`);
  console.error(
    "\n    למה זה חשוב: אלה ההיטלים שרכיבי הלקוח קוראים במקום מאגרי התוכן",
  );
  console.error("    המלאים. אם הם מיושנים, פירור לחם או טולטיפ יציגו טקסט ישן.");
  console.error("    תיקון: npm run generate:client-data ואז לשמור ב-git.\n");
  process.exit(1);
}

writeFileSync(crumbsPath, body, "utf8");
writeFileSync(glossaryPath, glossaryBody, "utf8");
console.log(
  `generate:client-data OK — ${Object.keys(blogTitles).length} פוסטים, ${Object.keys(serviceTitles).length} שירותים, ${GLOSSARY_TERMS.length} מונחים (hash ${hash}).`,
);
